// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/user/user_api.proto

package userapi

import (
	base "github.com/sbgayhub/golem/host/api/base"
	message "github.com/sbgayhub/golem/host/api/message"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetProfileResponse 获取用户资料响应（镜像 golem.user.GetProfileResponse）
type GetProfileResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	BaseResponse  *base.BaseResponse      `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	UserInfo      *message.ModifyUserInfo `protobuf:"bytes,2,opt,name=user_info,json=userInfo,proto3,oneof" json:"user_info,omitempty"`
	UserInfoExt   *message.UserInfoExtend `protobuf:"bytes,3,opt,name=user_info_ext,json=userInfoExt,proto3,oneof" json:"user_info_ext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_api_user_user_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_api_user_user_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetProfileResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *GetProfileResponse) GetUserInfo() *message.ModifyUserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

func (x *GetProfileResponse) GetUserInfoExt() *message.UserInfoExtend {
	if x != nil {
		return x.UserInfoExt
	}
	return nil
}

// UploadAvatarResponse 上传高清头像响应（镜像 golem.user.UploadAvatarResponse）
type UploadAvatarResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BaseResponse   *base.BaseResponse     `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	Size           *uint32                `protobuf:"varint,2,opt,name=size,proto3,oneof" json:"size,omitempty"`
	Offset         *uint32                `protobuf:"varint,3,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	FinalMd5       *string                `protobuf:"bytes,4,opt,name=final_md5,json=finalMd5,proto3,oneof" json:"final_md5,omitempty"`
	BigAvatarUrl   *string                `protobuf:"bytes,5,opt,name=big_avatar_url,json=bigAvatarUrl,proto3,oneof" json:"big_avatar_url,omitempty"`
	SmallAvatarUrl *string                `protobuf:"bytes,6,opt,name=small_avatar_url,json=smallAvatarUrl,proto3,oneof" json:"small_avatar_url,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UploadAvatarResponse) Reset() {
	*x = UploadAvatarResponse{}
	mi := &file_api_user_user_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAvatarResponse) ProtoMessage() {}

func (x *UploadAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAvatarResponse.ProtoReflect.Descriptor instead.
func (*UploadAvatarResponse) Descriptor() ([]byte, []int) {
	return file_api_user_user_api_proto_rawDescGZIP(), []int{1}
}

func (x *UploadAvatarResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *UploadAvatarResponse) GetSize() uint32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *UploadAvatarResponse) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *UploadAvatarResponse) GetFinalMd5() string {
	if x != nil && x.FinalMd5 != nil {
		return *x.FinalMd5
	}
	return ""
}

func (x *UploadAvatarResponse) GetBigAvatarUrl() string {
	if x != nil && x.BigAvatarUrl != nil {
		return *x.BigAvatarUrl
	}
	return ""
}

func (x *UploadAvatarResponse) GetSmallAvatarUrl() string {
	if x != nil && x.SmallAvatarUrl != nil {
		return *x.SmallAvatarUrl
	}
	return ""
}

// GetQRCodeResponse 获取二维码响应（镜像 golem.contact.GetQRCodeResponse）
type GetQRCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResponse  *base.BaseResponse     `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	QrcodeBuffer  *base.Buffer           `protobuf:"bytes,2,opt,name=qrcode_buffer,json=qrcodeBuffer,proto3,oneof" json:"qrcode_buffer,omitempty"`
	FooterWording *string                `protobuf:"bytes,3,opt,name=footer_wording,json=footerWording,proto3,oneof" json:"footer_wording,omitempty"`
	RevokeQrcode  *uint32                `protobuf:"varint,4,opt,name=revoke_qrcode,json=revokeQrcode,proto3,oneof" json:"revoke_qrcode,omitempty"`
	NotifyWording *string                `protobuf:"bytes,5,opt,name=notify_wording,json=notifyWording,proto3,oneof" json:"notify_wording,omitempty"`
	QrcodeUrl     *string                `protobuf:"bytes,6,opt,name=qrcode_url,json=qrcodeUrl,proto3,oneof" json:"qrcode_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQRCodeResponse) Reset() {
	*x = GetQRCodeResponse{}
	mi := &file_api_user_user_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQRCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQRCodeResponse) ProtoMessage() {}

func (x *GetQRCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQRCodeResponse.ProtoReflect.Descriptor instead.
func (*GetQRCodeResponse) Descriptor() ([]byte, []int) {
	return file_api_user_user_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetQRCodeResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *GetQRCodeResponse) GetQrcodeBuffer() *base.Buffer {
	if x != nil {
		return x.QrcodeBuffer
	}
	return nil
}

func (x *GetQRCodeResponse) GetFooterWording() string {
	if x != nil && x.FooterWording != nil {
		return *x.FooterWording
	}
	return ""
}

func (x *GetQRCodeResponse) GetRevokeQrcode() uint32 {
	if x != nil && x.RevokeQrcode != nil {
		return *x.RevokeQrcode
	}
	return 0
}

func (x *GetQRCodeResponse) GetNotifyWording() string {
	if x != nil && x.NotifyWording != nil {
		return *x.NotifyWording
	}
	return ""
}

func (x *GetQRCodeResponse) GetQrcodeUrl() string {
	if x != nil && x.QrcodeUrl != nil {
		return *x.QrcodeUrl
	}
	return ""
}

// BindEmailResponse 绑定邮箱响应（镜像 golem.user.BindEmailResponse）
type BindEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResponse  *base.BaseResponse     `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindEmailResponse) Reset() {
	*x = BindEmailResponse{}
	mi := &file_api_user_user_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindEmailResponse) ProtoMessage() {}

func (x *BindEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindEmailResponse.ProtoReflect.Descriptor instead.
func (*BindEmailResponse) Descriptor() ([]byte, []int) {
	return file_api_user_user_api_proto_rawDescGZIP(), []int{3}
}

func (x *BindEmailResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

// SendVerifyEmailResponse 发送验证邮件响应（镜像 golem.user.SendVerifyEmailResponse）
type SendVerifyEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResponse  *base.BaseResponse     `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendVerifyEmailResponse) Reset() {
	*x = SendVerifyEmailResponse{}
	mi := &file_api_user_user_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendVerifyEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVerifyEmailResponse) ProtoMessage() {}

func (x *SendVerifyEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVerifyEmailResponse.ProtoReflect.Descriptor instead.
func (*SendVerifyEmailResponse) Descriptor() ([]byte, []int) {
	return file_api_user_user_api_proto_rawDescGZIP(), []int{4}
}

func (x *SendVerifyEmailResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

// BindOpMobileResponse 绑定手机号/发送验证码响应（镜像 golem.user.BindOpMobileResponse）
type BindOpMobileResponse struct {
	state               protoimpl.MessageState               `protogen:"open.v1"`
	BaseResponse        *base.BaseResponse                   `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	Ticket              *string                              `protobuf:"bytes,2,opt,name=ticket,proto3,oneof" json:"ticket,omitempty"`
	SmsNo               *string                              `protobuf:"bytes,3,opt,name=sms_no,json=smsNo,proto3,oneof" json:"sms_no,omitempty"`
	NeedSetPassword     *uint32                              `protobuf:"varint,4,opt,name=need_set_password,json=needSetPassword,proto3,oneof" json:"need_set_password,omitempty"`
	Password            *string                              `protobuf:"bytes,5,opt,name=password,proto3,oneof" json:"password,omitempty"`
	Username            *string                              `protobuf:"bytes,6,opt,name=username,proto3,oneof" json:"username,omitempty"`
	NewHostList         *base.Hosts                          `protobuf:"bytes,7,opt,name=new_host_list,json=newHostList,proto3,oneof" json:"new_host_list,omitempty"`
	BuiltinIplist       *base.BuiltinIPList                  `protobuf:"bytes,8,opt,name=builtinIplist,proto3,oneof" json:"builtinIplist,omitempty"`
	NetworkControl      *base.NetworkControl                 `protobuf:"bytes,9,opt,name=network_control,json=networkControl,proto3,oneof" json:"network_control,omitempty"`
	AuthTicket          *string                              `protobuf:"bytes,10,opt,name=authTicket,proto3,oneof" json:"authTicket,omitempty"`
	SafeDevice          *uint32                              `protobuf:"varint,11,opt,name=safeDevice,proto3,oneof" json:"safeDevice,omitempty"`
	Cc                  *string                              `protobuf:"bytes,12,opt,name=cc,proto3,oneof" json:"cc,omitempty"`
	ObsoleteItem1       *uint32                              `protobuf:"varint,13,opt,name=obsoleteItem1,proto3,oneof" json:"obsoleteItem1,omitempty"`
	SafeDeviceList      *BindOpMobileResponse_SafeDeviceList `protobuf:"bytes,14,opt,name=safeDeviceList,proto3,oneof" json:"safeDeviceList,omitempty"`
	PureMobile          *string                              `protobuf:"bytes,15,opt,name=pureMobile,proto3,oneof" json:"pureMobile,omitempty"`
	FormatedMobile      *string                              `protobuf:"bytes,16,opt,name=formatedMobile,proto3,oneof" json:"formatedMobile,omitempty"`
	ShowStyle           *BindOpMobileResponse_ShowStyleKey   `protobuf:"bytes,17,opt,name=showStyle,proto3,oneof" json:"showStyle,omitempty"`
	MmtlsControlBitFlag *uint32                              `protobuf:"varint,18,opt,name=mmtlsControlBitFlag,proto3,oneof" json:"mmtlsControlBitFlag,omitempty"`
	SmsUpCode           *string                              `protobuf:"bytes,19,opt,name=smsUpCode,proto3,oneof" json:"smsUpCode,omitempty"`
	SmsUpMobile         *string                              `protobuf:"bytes,20,opt,name=smsUpMobile,proto3,oneof" json:"smsUpMobile,omitempty"`
	MobileCheckType     *uint32                              `protobuf:"varint,21,opt,name=mobileCheckType,proto3,oneof" json:"mobileCheckType,omitempty"`
	RegSessionId        *string                              `protobuf:"bytes,22,opt,name=regSessionId,proto3,oneof" json:"regSessionId,omitempty"`
	Restart             *uint32                              `protobuf:"varint,23,opt,name=restart,proto3,oneof" json:"restart,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BindOpMobileResponse) Reset() {
	*x = BindOpMobileResponse{}
	mi := &file_api_user_user_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindOpMobileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindOpMobileResponse) ProtoMessage() {}

func (x *BindOpMobileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindOpMobileResponse.ProtoReflect.Descriptor instead.
func (*BindOpMobileResponse) Descriptor() ([]byte, []int) {
	return file_api_user_user_api_proto_rawDescGZIP(), []int{5}
}

func (x *BindOpMobileResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *BindOpMobileResponse) GetTicket() string {
	if x != nil && x.Ticket != nil {
		return *x.Ticket
	}
	return ""
}

func (x *BindOpMobileResponse) GetSmsNo() string {
	if x != nil && x.SmsNo != nil {
		return *x.SmsNo
	}
	return ""
}

func (x *BindOpMobileResponse) GetNeedSetPassword() uint32 {
	if x != nil && x.NeedSetPassword != nil {
		return *x.NeedSetPassword
	}
	return 0
}

func (x *BindOpMobileResponse) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *BindOpMobileResponse) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *BindOpMobileResponse) GetNewHostList() *base.Hosts {
	if x != nil {
		return x.NewHostList
	}
	return nil
}

func (x *BindOpMobileResponse) GetBuiltinIplist() *base.BuiltinIPList {
	if x != nil {
		return x.BuiltinIplist
	}
	return nil
}

func (x *BindOpMobileResponse) GetNetworkControl() *base.NetworkControl {
	if x != nil {
		return x.NetworkControl
	}
	return nil
}

func (x *BindOpMobileResponse) GetAuthTicket() string {
	if x != nil && x.AuthTicket != nil {
		return *x.AuthTicket
	}
	return ""
}

func (x *BindOpMobileResponse) GetSafeDevice() uint32 {
	if x != nil && x.SafeDevice != nil {
		return *x.SafeDevice
	}
	return 0
}

func (x *BindOpMobileResponse) GetCc() string {
	if x != nil && x.Cc != nil {
		return *x.Cc
	}
	return ""
}

func (x *BindOpMobileResponse) GetObsoleteItem1() uint32 {
	if x != nil && x.ObsoleteItem1 != nil {
		return *x.ObsoleteItem1
	}
	return 0
}

func (x *BindOpMobileResponse) GetSafeDeviceList() *BindOpMobileResponse_SafeDeviceList {
	if x != nil {
		return x.SafeDeviceList
	}
	return nil
}

func (x *BindOpMobileResponse) GetPureMobile() string {
	if x != nil && x.PureMobile != nil {
		return *x.PureMobile
	}
	return ""
}

func (x *BindOpMobileResponse) GetFormatedMobile() string {
	if x != nil && x.FormatedMobile != nil {
		return *x.FormatedMobile
	}
	return ""
}

func (x *BindOpMobileResponse) GetShowStyle() *BindOpMobileResponse_ShowStyleKey {
	if x != nil {
		return x.ShowStyle
	}
	return nil
}

func (x *BindOpMobileResponse) GetMmtlsControlBitFlag() uint32 {
	if x != nil && x.MmtlsControlBitFlag != nil {
		return *x.MmtlsControlBitFlag
	}
	return 0
}

func (x *BindOpMobileResponse) GetSmsUpCode() string {
	if x != nil && x.SmsUpCode != nil {
		return *x.SmsUpCode
	}
	return ""
}

func (x *BindOpMobileResponse) GetSmsUpMobile() string {
	if x != nil && x.SmsUpMobile != nil {
		return *x.SmsUpMobile
	}
	return ""
}

func (x *BindOpMobileResponse) GetMobileCheckType() uint32 {
	if x != nil && x.MobileCheckType != nil {
		return *x.MobileCheckType
	}
	return 0
}

func (x *BindOpMobileResponse) GetRegSessionId() string {
	if x != nil && x.RegSessionId != nil {
		return *x.RegSessionId
	}
	return ""
}

func (x *BindOpMobileResponse) GetRestart() uint32 {
	if x != nil && x.Restart != nil {
		return *x.Restart
	}
	return 0
}

// SetPasswordResponse 修改密码响应（镜像 golem.user.SetPasswordResponse）
type SetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResponse  *base.BaseResponse     `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	AutoAuthKey   *base.Buffer           `protobuf:"bytes,2,opt,name=auto_auth_key,json=autoAuthKey,proto3,oneof" json:"auto_auth_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPasswordResponse) Reset() {
	*x = SetPasswordResponse{}
	mi := &file_api_user_user_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPasswordResponse) ProtoMessage() {}

func (x *SetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPasswordResponse.ProtoReflect.Descriptor instead.
func (*SetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_api_user_user_api_proto_rawDescGZIP(), []int{6}
}

func (x *SetPasswordResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *SetPasswordResponse) GetAutoAuthKey() *base.Buffer {
	if x != nil {
		return x.AutoAuthKey
	}
	return nil
}

// VerifyPasswordResponse 验证密码响应（镜像 golem.user.VerifyPasswordResponse）
type VerifyPasswordResponse struct {
	state                 protoimpl.MessageState  `protogen:"open.v1"`
	BaseResponse          *base.BaseResponse      `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	ImageSid              *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=image_sid,json=imageSid,proto3,oneof" json:"image_sid,omitempty"`
	ImageBuffer           *base.Buffer            `protobuf:"bytes,3,opt,name=image_buffer,json=imageBuffer,proto3,oneof" json:"image_buffer,omitempty"`
	Ticket                *string                 `protobuf:"bytes,4,opt,name=ticket,proto3,oneof" json:"ticket,omitempty"`
	ImageEncryptKey       *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=image_encrypt_key,json=imageEncryptKey,proto3,oneof" json:"image_encrypt_key,omitempty"`
	A2_Key                *base.Buffer            `protobuf:"bytes,6,opt,name=a2_Key,json=a2Key,proto3,oneof" json:"a2_Key,omitempty"`
	Ksid                  *base.Buffer            `protobuf:"bytes,7,opt,name=ksid,proto3,oneof" json:"ksid,omitempty"`
	AuthKey               *string                 `protobuf:"bytes,8,opt,name=auth_key,json=authKey,proto3,oneof" json:"auth_key,omitempty"`
	WtLoginResponseBuffer *base.Buffer            `protobuf:"bytes,9,opt,name=wt_login_response_buffer,json=wtLoginResponseBuffer,proto3,oneof" json:"wt_login_response_buffer,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *VerifyPasswordResponse) Reset() {
	*x = VerifyPasswordResponse{}
	mi := &file_api_user_user_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPasswordResponse) ProtoMessage() {}

func (x *VerifyPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPasswordResponse.ProtoReflect.Descriptor instead.
func (*VerifyPasswordResponse) Descriptor() ([]byte, []int) {
	return file_api_user_user_api_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyPasswordResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *VerifyPasswordResponse) GetImageSid() *wrapperspb.StringValue {
	if x != nil {
		return x.ImageSid
	}
	return nil
}

func (x *VerifyPasswordResponse) GetImageBuffer() *base.Buffer {
	if x != nil {
		return x.ImageBuffer
	}
	return nil
}

func (x *VerifyPasswordResponse) GetTicket() string {
	if x != nil && x.Ticket != nil {
		return *x.Ticket
	}
	return ""
}

func (x *VerifyPasswordResponse) GetImageEncryptKey() *wrapperspb.StringValue {
	if x != nil {
		return x.ImageEncryptKey
	}
	return nil
}

func (x *VerifyPasswordResponse) GetA2_Key() *base.Buffer {
	if x != nil {
		return x.A2_Key
	}
	return nil
}

func (x *VerifyPasswordResponse) GetKsid() *base.Buffer {
	if x != nil {
		return x.Ksid
	}
	return nil
}

func (x *VerifyPasswordResponse) GetAuthKey() string {
	if x != nil && x.AuthKey != nil {
		return *x.AuthKey
	}
	return ""
}

func (x *VerifyPasswordResponse) GetWtLoginResponseBuffer() *base.Buffer {
	if x != nil {
		return x.WtLoginResponseBuffer
	}
	return nil
}

// GetSafetyInfoResponse 获取安全设备列表响应（镜像 golem.user.GetSafetyInfoResponse）
type GetSafetyInfoResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	BaseResponse  *base.BaseResponse                `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	Info          *GetSafetyInfoResponse_SafetyInfo `protobuf:"bytes,2,opt,name=info,proto3,oneof" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSafetyInfoResponse) Reset() {
	*x = GetSafetyInfoResponse{}
	mi := &file_api_user_user_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSafetyInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSafetyInfoResponse) ProtoMessage() {}

func (x *GetSafetyInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSafetyInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSafetyInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_user_user_api_proto_rawDescGZIP(), []int{8}
}

func (x *GetSafetyInfoResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *GetSafetyInfoResponse) GetInfo() *GetSafetyInfoResponse_SafetyInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// DeleteSafeDeviceResponse 删除安全设备响应（镜像 golem.user.DeleteSafeDeviceResponse）
type DeleteSafeDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResponse  *base.BaseResponse     `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	RestCount     *uint64                `protobuf:"varint,2,opt,name=rest_count,json=restCount,proto3,oneof" json:"rest_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSafeDeviceResponse) Reset() {
	*x = DeleteSafeDeviceResponse{}
	mi := &file_api_user_user_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSafeDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSafeDeviceResponse) ProtoMessage() {}

func (x *DeleteSafeDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSafeDeviceResponse.ProtoReflect.Descriptor instead.
func (*DeleteSafeDeviceResponse) Descriptor() ([]byte, []int) {
	return file_api_user_user_api_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteSafeDeviceResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *DeleteSafeDeviceResponse) GetRestCount() uint64 {
	if x != nil && x.RestCount != nil {
		return *x.RestCount
	}
	return 0
}

// GeneralSetResponse 通用设置响应（镜像 golem.user.GeneralSetResponse）
type GeneralSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResponse  *base.BaseResponse     `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralSetResponse) Reset() {
	*x = GeneralSetResponse{}
	mi := &file_api_user_user_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralSetResponse) ProtoMessage() {}

func (x *GeneralSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralSetResponse.ProtoReflect.Descriptor instead.
func (*GeneralSetResponse) Descriptor() ([]byte, []int) {
	return file_api_user_user_api_proto_rawDescGZIP(), []int{10}
}

func (x *GeneralSetResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

// SportDeviceInfo 运动设备信息（镜像 golem.user.SportDeviceInfo）
type SportDeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BundleId      *string                `protobuf:"bytes,1,opt,name=bundle_id,json=bundleId,proto3,oneof" json:"bundle_id,omitempty"`
	AppName       *string                `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3,oneof" json:"app_name,omitempty"`
	StepCount     *uint32                `protobuf:"varint,3,opt,name=step_count,json=stepCount,proto3,oneof" json:"step_count,omitempty"`
	IsAppleWatch  *bool                  `protobuf:"varint,4,opt,name=is_apple_watch,json=isAppleWatch,proto3,oneof" json:"is_apple_watch,omitempty"`
	IsWhiteList   *bool                  `protobuf:"varint,5,opt,name=is_white_list,json=isWhiteList,proto3,oneof" json:"is_white_list,omitempty"`
	IsLocalIphone *bool                  `protobuf:"varint,6,opt,name=is_local_iphone,json=isLocalIphone,proto3,oneof" json:"is_local_iphone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SportDeviceInfo) Reset() {
	*x = SportDeviceInfo{}
	mi := &file_api_user_user_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SportDeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SportDeviceInfo) ProtoMessage() {}

func (x *SportDeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SportDeviceInfo.ProtoReflect.Descriptor instead.
func (*SportDeviceInfo) Descriptor() ([]byte, []int) {
	return file_api_user_user_api_proto_rawDescGZIP(), []int{11}
}

func (x *SportDeviceInfo) GetBundleId() string {
	if x != nil && x.BundleId != nil {
		return *x.BundleId
	}
	return ""
}

func (x *SportDeviceInfo) GetAppName() string {
	if x != nil && x.AppName != nil {
		return *x.AppName
	}
	return ""
}

func (x *SportDeviceInfo) GetStepCount() uint32 {
	if x != nil && x.StepCount != nil {
		return *x.StepCount
	}
	return 0
}

func (x *SportDeviceInfo) GetIsAppleWatch() bool {
	if x != nil && x.IsAppleWatch != nil {
		return *x.IsAppleWatch
	}
	return false
}

func (x *SportDeviceInfo) GetIsWhiteList() bool {
	if x != nil && x.IsWhiteList != nil {
		return *x.IsWhiteList
	}
	return false
}

func (x *SportDeviceInfo) GetIsLocalIphone() bool {
	if x != nil && x.IsLocalIphone != nil {
		return *x.IsLocalIphone
	}
	return false
}

// UploadDeviceStepResponse 上报设备步数响应（镜像 golem.user.UploadDeviceStepResponse）
type UploadDeviceStepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResponse  *base.BaseResponse     `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	DeviceInfo    *SportDeviceInfo       `protobuf:"bytes,2,opt,name=device_info,json=deviceInfo,proto3,oneof" json:"device_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDeviceStepResponse) Reset() {
	*x = UploadDeviceStepResponse{}
	mi := &file_api_user_user_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDeviceStepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDeviceStepResponse) ProtoMessage() {}

func (x *UploadDeviceStepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDeviceStepResponse.ProtoReflect.Descriptor instead.
func (*UploadDeviceStepResponse) Descriptor() ([]byte, []int) {
	return file_api_user_user_api_proto_rawDescGZIP(), []int{12}
}

func (x *UploadDeviceStepResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *UploadDeviceStepResponse) GetDeviceInfo() *SportDeviceInfo {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

// GetBoundHardDevicesResponse 获取绑定硬件设备响应（镜像 golem.user.GetBoundHardDevicesResponse）
type GetBoundHardDevicesResponse struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	BaseResponse  *base.BaseResponse                        `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	Count         *uint32                                   `protobuf:"varint,2,opt,name=count,proto3,oneof" json:"count,omitempty"`
	List          []*GetBoundHardDevicesResponse_HardDevice `protobuf:"bytes,5,rep,name=list,proto3" json:"list,omitempty"`
	Version       *int64                                    `protobuf:"varint,6,opt,name=version,proto3,oneof" json:"version,omitempty"`
	ContinueFlag  *int64                                    `protobuf:"varint,7,opt,name=continue_flag,json=continueFlag,proto3,oneof" json:"continue_flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoundHardDevicesResponse) Reset() {
	*x = GetBoundHardDevicesResponse{}
	mi := &file_api_user_user_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoundHardDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoundHardDevicesResponse) ProtoMessage() {}

func (x *GetBoundHardDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoundHardDevicesResponse.ProtoReflect.Descriptor instead.
func (*GetBoundHardDevicesResponse) Descriptor() ([]byte, []int) {
	return file_api_user_user_api_proto_rawDescGZIP(), []int{13}
}

func (x *GetBoundHardDevicesResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *GetBoundHardDevicesResponse) GetCount() uint32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *GetBoundHardDevicesResponse) GetList() []*GetBoundHardDevicesResponse_HardDevice {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetBoundHardDevicesResponse) GetVersion() int64 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *GetBoundHardDevicesResponse) GetContinueFlag() int64 {
	if x != nil && x.ContinueFlag != nil {
		return *x.ContinueFlag
	}
	return 0
}

// GetCertResponse 获取证书响应（镜像 golem.user.GetCertResponse）
type GetCertResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	BaseResponse  *base.BaseResponse       `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	Cert          *GetCertResponse_RSACert `protobuf:"bytes,2,opt,name=cert,proto3,oneof" json:"cert,omitempty"`
	CertVersion   *uint32                  `protobuf:"varint,3,opt,name=cert_version,json=certVersion,proto3,oneof" json:"cert_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertResponse) Reset() {
	*x = GetCertResponse{}
	mi := &file_api_user_user_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertResponse) ProtoMessage() {}

func (x *GetCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertResponse.ProtoReflect.Descriptor instead.
func (*GetCertResponse) Descriptor() ([]byte, []int) {
	return file_api_user_user_api_proto_rawDescGZIP(), []int{14}
}

func (x *GetCertResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *GetCertResponse) GetCert() *GetCertResponse_RSACert {
	if x != nil {
		return x.Cert
	}
	return nil
}

func (x *GetCertResponse) GetCertVersion() uint32 {
	if x != nil && x.CertVersion != nil {
		return *x.CertVersion
	}
	return 0
}

// SafeDeviceList 安全设备列表（镜像 golem.user.BindOpMobileResponse.SafeDeviceList）
type BindOpMobileResponse_SafeDeviceList struct {
	state         protoimpl.MessageState                            `protogen:"open.v1"`
	Count         *int32                                            `protobuf:"varint,1,opt,name=count,proto3,oneof" json:"count,omitempty"`
	List          []*BindOpMobileResponse_SafeDeviceList_SafeDevice `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindOpMobileResponse_SafeDeviceList) Reset() {
	*x = BindOpMobileResponse_SafeDeviceList{}
	mi := &file_api_user_user_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindOpMobileResponse_SafeDeviceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindOpMobileResponse_SafeDeviceList) ProtoMessage() {}

func (x *BindOpMobileResponse_SafeDeviceList) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindOpMobileResponse_SafeDeviceList.ProtoReflect.Descriptor instead.
func (*BindOpMobileResponse_SafeDeviceList) Descriptor() ([]byte, []int) {
	return file_api_user_user_api_proto_rawDescGZIP(), []int{5, 0}
}

func (x *BindOpMobileResponse_SafeDeviceList) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *BindOpMobileResponse_SafeDeviceList) GetList() []*BindOpMobileResponse_SafeDeviceList_SafeDevice {
	if x != nil {
		return x.List
	}
	return nil
}

// ShowStyleKey 展示样式键值（镜像 golem.user.BindOpMobileResponse.ShowStyleKey）
type BindOpMobileResponse_ShowStyleKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           uint32                 `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *string                `protobuf:"bytes,2,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindOpMobileResponse_ShowStyleKey) Reset() {
	*x = BindOpMobileResponse_ShowStyleKey{}
	mi := &file_api_user_user_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindOpMobileResponse_ShowStyleKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindOpMobileResponse_ShowStyleKey) ProtoMessage() {}

func (x *BindOpMobileResponse_ShowStyleKey) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindOpMobileResponse_ShowStyleKey.ProtoReflect.Descriptor instead.
func (*BindOpMobileResponse_ShowStyleKey) Descriptor() ([]byte, []int) {
	return file_api_user_user_api_proto_rawDescGZIP(), []int{5, 1}
}

func (x *BindOpMobileResponse_ShowStyleKey) GetKey() uint32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *BindOpMobileResponse_ShowStyleKey) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

// SafeDevice 安全设备（镜像 golem.user.BindOpMobileResponse.SafeDeviceList.SafeDevice）
type BindOpMobileResponse_SafeDeviceList_SafeDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Uuid          *string                `protobuf:"bytes,2,opt,name=uuid,proto3,oneof" json:"uuid,omitempty"`
	Type          *string                `protobuf:"bytes,3,opt,name=type,proto3,oneof" json:"type,omitempty"`
	CreateTime    *uint32                `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3,oneof" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindOpMobileResponse_SafeDeviceList_SafeDevice) Reset() {
	*x = BindOpMobileResponse_SafeDeviceList_SafeDevice{}
	mi := &file_api_user_user_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindOpMobileResponse_SafeDeviceList_SafeDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindOpMobileResponse_SafeDeviceList_SafeDevice) ProtoMessage() {}

func (x *BindOpMobileResponse_SafeDeviceList_SafeDevice) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindOpMobileResponse_SafeDeviceList_SafeDevice.ProtoReflect.Descriptor instead.
func (*BindOpMobileResponse_SafeDeviceList_SafeDevice) Descriptor() ([]byte, []int) {
	return file_api_user_user_api_proto_rawDescGZIP(), []int{5, 0, 0}
}

func (x *BindOpMobileResponse_SafeDeviceList_SafeDevice) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *BindOpMobileResponse_SafeDeviceList_SafeDevice) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *BindOpMobileResponse_SafeDeviceList_SafeDevice) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *BindOpMobileResponse_SafeDeviceList_SafeDevice) GetCreateTime() uint32 {
	if x != nil && x.CreateTime != nil {
		return *x.CreateTime
	}
	return 0
}

// SafetyDevice 安全设备（镜像 golem.user.GetSafetyInfoResponse.SafetyDevice）
type GetSafetyInfoResponse_SafetyDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          *string                `protobuf:"bytes,1,opt,name=uuid,proto3,oneof" json:"uuid,omitempty"`
	DeviceName    *string                `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3,oneof" json:"device_name,omitempty"`
	DeviceType    *string                `protobuf:"bytes,3,opt,name=device_type,json=deviceType,proto3,oneof" json:"device_type,omitempty"`
	LastTime      *uint64                `protobuf:"varint,4,opt,name=last_time,json=lastTime,proto3,oneof" json:"last_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSafetyInfoResponse_SafetyDevice) Reset() {
	*x = GetSafetyInfoResponse_SafetyDevice{}
	mi := &file_api_user_user_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSafetyInfoResponse_SafetyDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSafetyInfoResponse_SafetyDevice) ProtoMessage() {}

func (x *GetSafetyInfoResponse_SafetyDevice) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSafetyInfoResponse_SafetyDevice.ProtoReflect.Descriptor instead.
func (*GetSafetyInfoResponse_SafetyDevice) Descriptor() ([]byte, []int) {
	return file_api_user_user_api_proto_rawDescGZIP(), []int{8, 0}
}

func (x *GetSafetyInfoResponse_SafetyDevice) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *GetSafetyInfoResponse_SafetyDevice) GetDeviceName() string {
	if x != nil && x.DeviceName != nil {
		return *x.DeviceName
	}
	return ""
}

func (x *GetSafetyInfoResponse_SafetyDevice) GetDeviceType() string {
	if x != nil && x.DeviceType != nil {
		return *x.DeviceType
	}
	return ""
}

func (x *GetSafetyInfoResponse_SafetyDevice) GetLastTime() uint64 {
	if x != nil && x.LastTime != nil {
		return *x.LastTime
	}
	return 0
}

// SafetyInfo 安全信息（镜像 golem.user.GetSafetyInfoResponse.SafetyInfo）
type GetSafetyInfoResponse_SafetyInfo struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	DeviceList    []*GetSafetyInfoResponse_SafetyDevice `protobuf:"bytes,1,rep,name=device_list,json=deviceList,proto3" json:"device_list,omitempty"`
	HasVoice      *bool                                 `protobuf:"varint,2,opt,name=has_voice,json=hasVoice,proto3,oneof" json:"has_voice,omitempty"`
	SwitchVoice   *bool                                 `protobuf:"varint,3,opt,name=switch_voice,json=switchVoice,proto3,oneof" json:"switch_voice,omitempty"`
	HasFace       *bool                                 `protobuf:"varint,4,opt,name=has_face,json=hasFace,proto3,oneof" json:"has_face,omitempty"`
	SwitchFace    *bool                                 `protobuf:"varint,5,opt,name=switch_face,json=switchFace,proto3,oneof" json:"switch_face,omitempty"`
	HasPassword   *bool                                 `protobuf:"varint,6,opt,name=has_password,json=hasPassword,proto3,oneof" json:"has_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSafetyInfoResponse_SafetyInfo) Reset() {
	*x = GetSafetyInfoResponse_SafetyInfo{}
	mi := &file_api_user_user_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSafetyInfoResponse_SafetyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSafetyInfoResponse_SafetyInfo) ProtoMessage() {}

func (x *GetSafetyInfoResponse_SafetyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSafetyInfoResponse_SafetyInfo.ProtoReflect.Descriptor instead.
func (*GetSafetyInfoResponse_SafetyInfo) Descriptor() ([]byte, []int) {
	return file_api_user_user_api_proto_rawDescGZIP(), []int{8, 1}
}

func (x *GetSafetyInfoResponse_SafetyInfo) GetDeviceList() []*GetSafetyInfoResponse_SafetyDevice {
	if x != nil {
		return x.DeviceList
	}
	return nil
}

func (x *GetSafetyInfoResponse_SafetyInfo) GetHasVoice() bool {
	if x != nil && x.HasVoice != nil {
		return *x.HasVoice
	}
	return false
}

func (x *GetSafetyInfoResponse_SafetyInfo) GetSwitchVoice() bool {
	if x != nil && x.SwitchVoice != nil {
		return *x.SwitchVoice
	}
	return false
}

func (x *GetSafetyInfoResponse_SafetyInfo) GetHasFace() bool {
	if x != nil && x.HasFace != nil {
		return *x.HasFace
	}
	return false
}

func (x *GetSafetyInfoResponse_SafetyInfo) GetSwitchFace() bool {
	if x != nil && x.SwitchFace != nil {
		return *x.SwitchFace
	}
	return false
}

func (x *GetSafetyInfoResponse_SafetyInfo) GetHasPassword() bool {
	if x != nil && x.HasPassword != nil {
		return *x.HasPassword
	}
	return false
}

// HardDevice 绑定硬件设备（镜像 golem.user.GetBoundHardDevicesResponse.HardDevice）
type GetBoundHardDevicesResponse_HardDevice struct {
	state         protoimpl.MessageState                            `protogen:"open.v1"`
	Device        *GetBoundHardDevicesResponse_HardDevice_Device    `protobuf:"bytes,1,opt,name=device,proto3,oneof" json:"device,omitempty"`
	Attribute     *GetBoundHardDevicesResponse_HardDevice_Attribute `protobuf:"bytes,2,opt,name=attribute,proto3,oneof" json:"attribute,omitempty"`
	Flag          *uint32                                           `protobuf:"varint,3,opt,name=flag,proto3,oneof" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoundHardDevicesResponse_HardDevice) Reset() {
	*x = GetBoundHardDevicesResponse_HardDevice{}
	mi := &file_api_user_user_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoundHardDevicesResponse_HardDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoundHardDevicesResponse_HardDevice) ProtoMessage() {}

func (x *GetBoundHardDevicesResponse_HardDevice) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoundHardDevicesResponse_HardDevice.ProtoReflect.Descriptor instead.
func (*GetBoundHardDevicesResponse_HardDevice) Descriptor() ([]byte, []int) {
	return file_api_user_user_api_proto_rawDescGZIP(), []int{13, 0}
}

func (x *GetBoundHardDevicesResponse_HardDevice) GetDevice() *GetBoundHardDevicesResponse_HardDevice_Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *GetBoundHardDevicesResponse_HardDevice) GetAttribute() *GetBoundHardDevicesResponse_HardDevice_Attribute {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *GetBoundHardDevicesResponse_HardDevice) GetFlag() uint32 {
	if x != nil && x.Flag != nil {
		return *x.Flag
	}
	return 0
}

// Device 设备信息（镜像 golem.user.GetBoundHardDevicesResponse.HardDevice.Device）
type GetBoundHardDevicesResponse_HardDevice_Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Id            *string                `protobuf:"bytes,2,opt,name=id,proto3,oneof" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoundHardDevicesResponse_HardDevice_Device) Reset() {
	*x = GetBoundHardDevicesResponse_HardDevice_Device{}
	mi := &file_api_user_user_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoundHardDevicesResponse_HardDevice_Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoundHardDevicesResponse_HardDevice_Device) ProtoMessage() {}

func (x *GetBoundHardDevicesResponse_HardDevice_Device) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoundHardDevicesResponse_HardDevice_Device.ProtoReflect.Descriptor instead.
func (*GetBoundHardDevicesResponse_HardDevice_Device) Descriptor() ([]byte, []int) {
	return file_api_user_user_api_proto_rawDescGZIP(), []int{13, 0, 0}
}

func (x *GetBoundHardDevicesResponse_HardDevice_Device) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *GetBoundHardDevicesResponse_HardDevice_Device) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

// Attribute 设备属性（镜像 golem.user.GetBoundHardDevicesResponse.HardDevice.Attribute）
type GetBoundHardDevicesResponse_HardDevice_Attribute struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BrandName            *string                `protobuf:"bytes,1,opt,name=brand_name,json=brandName,proto3,oneof" json:"brand_name,omitempty"`
	AuthKey              *string                `protobuf:"bytes,2,opt,name=auth_key,json=authKey,proto3,oneof" json:"auth_key,omitempty"`
	Mac                  *string                `protobuf:"bytes,3,opt,name=mac,proto3,oneof" json:"mac,omitempty"`
	ConnProto            *string                `protobuf:"bytes,4,opt,name=conn_proto,json=connProto,proto3,oneof" json:"conn_proto,omitempty"`
	ConnStrategy         *uint32                `protobuf:"varint,5,opt,name=conn_strategy,json=connStrategy,proto3,oneof" json:"conn_strategy,omitempty"`
	CloseStrategy        *uint32                `protobuf:"varint,6,opt,name=close_strategy,json=closeStrategy,proto3,oneof" json:"close_strategy,omitempty"`
	ManuMacPos           *int32                 `protobuf:"varint,7,opt,name=manu_mac_pos,json=manuMacPos,proto3,oneof" json:"manu_mac_pos,omitempty"`
	SerMacPos            *int32                 `protobuf:"varint,8,opt,name=ser_mac_pos,json=serMacPos,proto3,oneof" json:"ser_mac_pos,omitempty"`
	AttributeDescription *string                `protobuf:"bytes,9,opt,name=attribute_description,json=attributeDescription,proto3,oneof" json:"attribute_description,omitempty"`
	Alias                *string                `protobuf:"bytes,10,opt,name=alias,proto3,oneof" json:"alias,omitempty"`
	IconUrl              *string                `protobuf:"bytes,11,opt,name=icon_url,json=iconUrl,proto3,oneof" json:"icon_url,omitempty"`
	JumpUrl              *string                `protobuf:"bytes,12,opt,name=jump_url,json=jumpUrl,proto3,oneof" json:"jump_url,omitempty"`
	DeviceTitle          *string                `protobuf:"bytes,13,opt,name=device_title,json=deviceTitle,proto3,oneof" json:"device_title,omitempty"`
	DeviceDescription    *string                `protobuf:"bytes,14,opt,name=device_description,json=deviceDescription,proto3,oneof" json:"device_description,omitempty"`
	Category             *string                `protobuf:"bytes,15,opt,name=category,proto3,oneof" json:"category,omitempty"`
	DeviceTypeMainDevice *uint32                `protobuf:"varint,16,opt,name=device_type_main_device,json=deviceTypeMainDevice,proto3,oneof" json:"device_type_main_device,omitempty"`
	IsEnterMyDevice      *uint32                `protobuf:"varint,17,opt,name=is_enter_my_device,json=isEnterMyDevice,proto3,oneof" json:"is_enter_my_device,omitempty"`
	BleSimpleProtocol    *int64                 `protobuf:"varint,18,opt,name=ble_simple_protocol,json=bleSimpleProtocol,proto3,oneof" json:"ble_simple_protocol,omitempty"`
	Ability              *string                `protobuf:"bytes,19,opt,name=ability,proto3,oneof" json:"ability,omitempty"`
	AbilityInfo          *string                `protobuf:"bytes,20,opt,name=ability_info,json=abilityInfo,proto3,oneof" json:"ability_info,omitempty"`
	SerialNumber         *string                `protobuf:"bytes,21,opt,name=serial_number,json=serialNumber,proto3,oneof" json:"serial_number,omitempty"`
	SubDeviceList        *string                `protobuf:"bytes,22,opt,name=sub_device_list,json=subDeviceList,proto3,oneof" json:"sub_device_list,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) Reset() {
	*x = GetBoundHardDevicesResponse_HardDevice_Attribute{}
	mi := &file_api_user_user_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoundHardDevicesResponse_HardDevice_Attribute) ProtoMessage() {}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoundHardDevicesResponse_HardDevice_Attribute.ProtoReflect.Descriptor instead.
func (*GetBoundHardDevicesResponse_HardDevice_Attribute) Descriptor() ([]byte, []int) {
	return file_api_user_user_api_proto_rawDescGZIP(), []int{13, 0, 1}
}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) GetBrandName() string {
	if x != nil && x.BrandName != nil {
		return *x.BrandName
	}
	return ""
}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) GetAuthKey() string {
	if x != nil && x.AuthKey != nil {
		return *x.AuthKey
	}
	return ""
}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) GetMac() string {
	if x != nil && x.Mac != nil {
		return *x.Mac
	}
	return ""
}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) GetConnProto() string {
	if x != nil && x.ConnProto != nil {
		return *x.ConnProto
	}
	return ""
}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) GetConnStrategy() uint32 {
	if x != nil && x.ConnStrategy != nil {
		return *x.ConnStrategy
	}
	return 0
}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) GetCloseStrategy() uint32 {
	if x != nil && x.CloseStrategy != nil {
		return *x.CloseStrategy
	}
	return 0
}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) GetManuMacPos() int32 {
	if x != nil && x.ManuMacPos != nil {
		return *x.ManuMacPos
	}
	return 0
}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) GetSerMacPos() int32 {
	if x != nil && x.SerMacPos != nil {
		return *x.SerMacPos
	}
	return 0
}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) GetAttributeDescription() string {
	if x != nil && x.AttributeDescription != nil {
		return *x.AttributeDescription
	}
	return ""
}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) GetIconUrl() string {
	if x != nil && x.IconUrl != nil {
		return *x.IconUrl
	}
	return ""
}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) GetJumpUrl() string {
	if x != nil && x.JumpUrl != nil {
		return *x.JumpUrl
	}
	return ""
}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) GetDeviceTitle() string {
	if x != nil && x.DeviceTitle != nil {
		return *x.DeviceTitle
	}
	return ""
}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) GetDeviceDescription() string {
	if x != nil && x.DeviceDescription != nil {
		return *x.DeviceDescription
	}
	return ""
}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) GetDeviceTypeMainDevice() uint32 {
	if x != nil && x.DeviceTypeMainDevice != nil {
		return *x.DeviceTypeMainDevice
	}
	return 0
}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) GetIsEnterMyDevice() uint32 {
	if x != nil && x.IsEnterMyDevice != nil {
		return *x.IsEnterMyDevice
	}
	return 0
}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) GetBleSimpleProtocol() int64 {
	if x != nil && x.BleSimpleProtocol != nil {
		return *x.BleSimpleProtocol
	}
	return 0
}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) GetAbility() string {
	if x != nil && x.Ability != nil {
		return *x.Ability
	}
	return ""
}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) GetAbilityInfo() string {
	if x != nil && x.AbilityInfo != nil {
		return *x.AbilityInfo
	}
	return ""
}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) GetSerialNumber() string {
	if x != nil && x.SerialNumber != nil {
		return *x.SerialNumber
	}
	return ""
}

func (x *GetBoundHardDevicesResponse_HardDevice_Attribute) GetSubDeviceList() string {
	if x != nil && x.SubDeviceList != nil {
		return *x.SubDeviceList
	}
	return ""
}

// RSACert RSA 证书（镜像 golem.user.GetCertResponse.RSACert）
type GetCertResponse_RSACert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyN          *string                `protobuf:"bytes,1,opt,name=key_n,json=keyN,proto3,oneof" json:"key_n,omitempty"`
	KeyE          *string                `protobuf:"bytes,2,opt,name=key_e,json=keyE,proto3,oneof" json:"key_e,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertResponse_RSACert) Reset() {
	*x = GetCertResponse_RSACert{}
	mi := &file_api_user_user_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertResponse_RSACert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertResponse_RSACert) ProtoMessage() {}

func (x *GetCertResponse_RSACert) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_user_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertResponse_RSACert.ProtoReflect.Descriptor instead.
func (*GetCertResponse_RSACert) Descriptor() ([]byte, []int) {
	return file_api_user_user_api_proto_rawDescGZIP(), []int{14, 0}
}

func (x *GetCertResponse_RSACert) GetKeyN() string {
	if x != nil && x.KeyN != nil {
		return *x.KeyN
	}
	return ""
}

func (x *GetCertResponse_RSACert) GetKeyE() string {
	if x != nil && x.KeyE != nil {
		return *x.KeyE
	}
	return ""
}

var File_api_user_user_api_proto protoreflect.FileDescriptor

const file_api_user_user_api_proto_rawDesc = "" +
	"\n" +
	"\x17api/user/user_api.proto\x12\bapi.user\x1a\x13api/base/base.proto\x1a\x1capi/message/sync_types.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x8d\x02\n" +
	"\x12GetProfileResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x12=\n" +
	"\tuser_info\x18\x02 \x01(\v2\x1b.api.message.ModifyUserInfoH\x01R\buserInfo\x88\x01\x01\x12D\n" +
	"\ruser_info_ext\x18\x03 \x01(\v2\x1b.api.message.UserInfoExtendH\x02R\vuserInfoExt\x88\x01\x01B\x10\n" +
	"\x0e_base_responseB\f\n" +
	"\n" +
	"_user_infoB\x10\n" +
	"\x0e_user_info_ext\"\xe6\x02\n" +
	"\x14UploadAvatarResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\x02 \x01(\rH\x01R\x04size\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x03 \x01(\rH\x02R\x06offset\x88\x01\x01\x12 \n" +
	"\tfinal_md5\x18\x04 \x01(\tH\x03R\bfinalMd5\x88\x01\x01\x12)\n" +
	"\x0ebig_avatar_url\x18\x05 \x01(\tH\x04R\fbigAvatarUrl\x88\x01\x01\x12-\n" +
	"\x10small_avatar_url\x18\x06 \x01(\tH\x05R\x0esmallAvatarUrl\x88\x01\x01B\x10\n" +
	"\x0e_base_responseB\a\n" +
	"\x05_sizeB\t\n" +
	"\a_offsetB\f\n" +
	"\n" +
	"_final_md5B\x11\n" +
	"\x0f_big_avatar_urlB\x13\n" +
	"\x11_small_avatar_url\"\xa2\x03\n" +
	"\x11GetQRCodeResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x12:\n" +
	"\rqrcode_buffer\x18\x02 \x01(\v2\x10.api.base.BufferH\x01R\fqrcodeBuffer\x88\x01\x01\x12*\n" +
	"\x0efooter_wording\x18\x03 \x01(\tH\x02R\rfooterWording\x88\x01\x01\x12(\n" +
	"\rrevoke_qrcode\x18\x04 \x01(\rH\x03R\frevokeQrcode\x88\x01\x01\x12*\n" +
	"\x0enotify_wording\x18\x05 \x01(\tH\x04R\rnotifyWording\x88\x01\x01\x12\"\n" +
	"\n" +
	"qrcode_url\x18\x06 \x01(\tH\x05R\tqrcodeUrl\x88\x01\x01B\x10\n" +
	"\x0e_base_responseB\x10\n" +
	"\x0e_qrcode_bufferB\x11\n" +
	"\x0f_footer_wordingB\x10\n" +
	"\x0e_revoke_qrcodeB\x11\n" +
	"\x0f_notify_wordingB\r\n" +
	"\v_qrcode_url\"g\n" +
	"\x11BindEmailResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01B\x10\n" +
	"\x0e_base_response\"m\n" +
	"\x17SendVerifyEmailResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01B\x10\n" +
	"\x0e_base_response\"\xb3\x0e\n" +
	"\x14BindOpMobileResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x12\x1b\n" +
	"\x06ticket\x18\x02 \x01(\tH\x01R\x06ticket\x88\x01\x01\x12\x1a\n" +
	"\x06sms_no\x18\x03 \x01(\tH\x02R\x05smsNo\x88\x01\x01\x12/\n" +
	"\x11need_set_password\x18\x04 \x01(\rH\x03R\x0fneedSetPassword\x88\x01\x01\x12\x1f\n" +
	"\bpassword\x18\x05 \x01(\tH\x04R\bpassword\x88\x01\x01\x12\x1f\n" +
	"\busername\x18\x06 \x01(\tH\x05R\busername\x88\x01\x01\x128\n" +
	"\rnew_host_list\x18\a \x01(\v2\x0f.api.base.HostsH\x06R\vnewHostList\x88\x01\x01\x12B\n" +
	"\rbuiltinIplist\x18\b \x01(\v2\x17.api.base.BuiltinIPListH\aR\rbuiltinIplist\x88\x01\x01\x12F\n" +
	"\x0fnetwork_control\x18\t \x01(\v2\x18.api.base.NetworkControlH\bR\x0enetworkControl\x88\x01\x01\x12#\n" +
	"\n" +
	"authTicket\x18\n" +
	" \x01(\tH\tR\n" +
	"authTicket\x88\x01\x01\x12#\n" +
	"\n" +
	"safeDevice\x18\v \x01(\rH\n" +
	"R\n" +
	"safeDevice\x88\x01\x01\x12\x13\n" +
	"\x02cc\x18\f \x01(\tH\vR\x02cc\x88\x01\x01\x12)\n" +
	"\robsoleteItem1\x18\r \x01(\rH\fR\robsoleteItem1\x88\x01\x01\x12Z\n" +
	"\x0esafeDeviceList\x18\x0e \x01(\v2-.api.user.BindOpMobileResponse.SafeDeviceListH\rR\x0esafeDeviceList\x88\x01\x01\x12#\n" +
	"\n" +
	"pureMobile\x18\x0f \x01(\tH\x0eR\n" +
	"pureMobile\x88\x01\x01\x12+\n" +
	"\x0eformatedMobile\x18\x10 \x01(\tH\x0fR\x0eformatedMobile\x88\x01\x01\x12N\n" +
	"\tshowStyle\x18\x11 \x01(\v2+.api.user.BindOpMobileResponse.ShowStyleKeyH\x10R\tshowStyle\x88\x01\x01\x125\n" +
	"\x13mmtlsControlBitFlag\x18\x12 \x01(\rH\x11R\x13mmtlsControlBitFlag\x88\x01\x01\x12!\n" +
	"\tsmsUpCode\x18\x13 \x01(\tH\x12R\tsmsUpCode\x88\x01\x01\x12%\n" +
	"\vsmsUpMobile\x18\x14 \x01(\tH\x13R\vsmsUpMobile\x88\x01\x01\x12-\n" +
	"\x0fmobileCheckType\x18\x15 \x01(\rH\x14R\x0fmobileCheckType\x88\x01\x01\x12'\n" +
	"\fregSessionId\x18\x16 \x01(\tH\x15R\fregSessionId\x88\x01\x01\x12\x1d\n" +
	"\arestart\x18\x17 \x01(\rH\x16R\arestart\x88\x01\x01\x1a\xae\x02\n" +
	"\x0eSafeDeviceList\x12\x19\n" +
	"\x05count\x18\x01 \x01(\x05H\x00R\x05count\x88\x01\x01\x12L\n" +
	"\x04list\x18\x02 \x03(\v28.api.user.BindOpMobileResponse.SafeDeviceList.SafeDeviceR\x04list\x1a\xa8\x01\n" +
	"\n" +
	"SafeDevice\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x17\n" +
	"\x04uuid\x18\x02 \x01(\tH\x01R\x04uuid\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\x03 \x01(\tH\x02R\x04type\x88\x01\x01\x12$\n" +
	"\vcreate_time\x18\x04 \x01(\rH\x03R\n" +
	"createTime\x88\x01\x01B\a\n" +
	"\x05_nameB\a\n" +
	"\x05_uuidB\a\n" +
	"\x05_typeB\x0e\n" +
	"\f_create_timeB\b\n" +
	"\x06_count\x1aE\n" +
	"\fShowStyleKey\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x19\n" +
	"\x05value\x18\x02 \x01(\tH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_valueB\x10\n" +
	"\x0e_base_responseB\t\n" +
	"\a_ticketB\t\n" +
	"\a_sms_noB\x14\n" +
	"\x12_need_set_passwordB\v\n" +
	"\t_passwordB\v\n" +
	"\t_usernameB\x10\n" +
	"\x0e_new_host_listB\x10\n" +
	"\x0e_builtinIplistB\x12\n" +
	"\x10_network_controlB\r\n" +
	"\v_authTicketB\r\n" +
	"\v_safeDeviceB\x05\n" +
	"\x03_ccB\x10\n" +
	"\x0e_obsoleteItem1B\x11\n" +
	"\x0f_safeDeviceListB\r\n" +
	"\v_pureMobileB\x11\n" +
	"\x0f_formatedMobileB\f\n" +
	"\n" +
	"_showStyleB\x16\n" +
	"\x14_mmtlsControlBitFlagB\f\n" +
	"\n" +
	"_smsUpCodeB\x0e\n" +
	"\f_smsUpMobileB\x12\n" +
	"\x10_mobileCheckTypeB\x0f\n" +
	"\r_regSessionIdB\n" +
	"\n" +
	"\b_restart\"\xb6\x01\n" +
	"\x13SetPasswordResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x129\n" +
	"\rauto_auth_key\x18\x02 \x01(\v2\x10.api.base.BufferH\x01R\vautoAuthKey\x88\x01\x01B\x10\n" +
	"\x0e_base_responseB\x10\n" +
	"\x0e_auto_auth_key\"\x99\x05\n" +
	"\x16VerifyPasswordResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x12>\n" +
	"\timage_sid\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueH\x01R\bimageSid\x88\x01\x01\x128\n" +
	"\fimage_buffer\x18\x03 \x01(\v2\x10.api.base.BufferH\x02R\vimageBuffer\x88\x01\x01\x12\x1b\n" +
	"\x06ticket\x18\x04 \x01(\tH\x03R\x06ticket\x88\x01\x01\x12M\n" +
	"\x11image_encrypt_key\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueH\x04R\x0fimageEncryptKey\x88\x01\x01\x12,\n" +
	"\x06a2_Key\x18\x06 \x01(\v2\x10.api.base.BufferH\x05R\x05a2Key\x88\x01\x01\x12)\n" +
	"\x04ksid\x18\a \x01(\v2\x10.api.base.BufferH\x06R\x04ksid\x88\x01\x01\x12\x1e\n" +
	"\bauth_key\x18\b \x01(\tH\aR\aauthKey\x88\x01\x01\x12N\n" +
	"\x18wt_login_response_buffer\x18\t \x01(\v2\x10.api.base.BufferH\bR\x15wtLoginResponseBuffer\x88\x01\x01B\x10\n" +
	"\x0e_base_responseB\f\n" +
	"\n" +
	"_image_sidB\x0f\n" +
	"\r_image_bufferB\t\n" +
	"\a_ticketB\x14\n" +
	"\x12_image_encrypt_keyB\t\n" +
	"\a_a2_KeyB\a\n" +
	"\x05_ksidB\v\n" +
	"\t_auth_keyB\x1b\n" +
	"\x19_wt_login_response_buffer\"\xeb\x05\n" +
	"\x15GetSafetyInfoResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x12C\n" +
	"\x04info\x18\x02 \x01(\v2*.api.user.GetSafetyInfoResponse.SafetyInfoH\x01R\x04info\x88\x01\x01\x1a\xcc\x01\n" +
	"\fSafetyDevice\x12\x17\n" +
	"\x04uuid\x18\x01 \x01(\tH\x00R\x04uuid\x88\x01\x01\x12$\n" +
	"\vdevice_name\x18\x02 \x01(\tH\x01R\n" +
	"deviceName\x88\x01\x01\x12$\n" +
	"\vdevice_type\x18\x03 \x01(\tH\x02R\n" +
	"deviceType\x88\x01\x01\x12 \n" +
	"\tlast_time\x18\x04 \x01(\x04H\x03R\blastTime\x88\x01\x01B\a\n" +
	"\x05_uuidB\x0e\n" +
	"\f_device_nameB\x0e\n" +
	"\f_device_typeB\f\n" +
	"\n" +
	"_last_time\x1a\xe0\x02\n" +
	"\n" +
	"SafetyInfo\x12M\n" +
	"\vdevice_list\x18\x01 \x03(\v2,.api.user.GetSafetyInfoResponse.SafetyDeviceR\n" +
	"deviceList\x12 \n" +
	"\thas_voice\x18\x02 \x01(\bH\x00R\bhasVoice\x88\x01\x01\x12&\n" +
	"\fswitch_voice\x18\x03 \x01(\bH\x01R\vswitchVoice\x88\x01\x01\x12\x1e\n" +
	"\bhas_face\x18\x04 \x01(\bH\x02R\ahasFace\x88\x01\x01\x12$\n" +
	"\vswitch_face\x18\x05 \x01(\bH\x03R\n" +
	"switchFace\x88\x01\x01\x12&\n" +
	"\fhas_password\x18\x06 \x01(\bH\x04R\vhasPassword\x88\x01\x01B\f\n" +
	"\n" +
	"_has_voiceB\x0f\n" +
	"\r_switch_voiceB\v\n" +
	"\t_has_faceB\x0e\n" +
	"\f_switch_faceB\x0f\n" +
	"\r_has_passwordB\x10\n" +
	"\x0e_base_responseB\a\n" +
	"\x05_info\"\xa1\x01\n" +
	"\x18DeleteSafeDeviceResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x12\"\n" +
	"\n" +
	"rest_count\x18\x02 \x01(\x04H\x01R\trestCount\x88\x01\x01B\x10\n" +
	"\x0e_base_responseB\r\n" +
	"\v_rest_count\"h\n" +
	"\x12GeneralSetResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01B\x10\n" +
	"\x0e_base_response\"\xdb\x02\n" +
	"\x0fSportDeviceInfo\x12 \n" +
	"\tbundle_id\x18\x01 \x01(\tH\x00R\bbundleId\x88\x01\x01\x12\x1e\n" +
	"\bapp_name\x18\x02 \x01(\tH\x01R\aappName\x88\x01\x01\x12\"\n" +
	"\n" +
	"step_count\x18\x03 \x01(\rH\x02R\tstepCount\x88\x01\x01\x12)\n" +
	"\x0eis_apple_watch\x18\x04 \x01(\bH\x03R\fisAppleWatch\x88\x01\x01\x12'\n" +
	"\ris_white_list\x18\x05 \x01(\bH\x04R\visWhiteList\x88\x01\x01\x12+\n" +
	"\x0fis_local_iphone\x18\x06 \x01(\bH\x05R\risLocalIphone\x88\x01\x01B\f\n" +
	"\n" +
	"_bundle_idB\v\n" +
	"\t_app_nameB\r\n" +
	"\v_step_countB\x11\n" +
	"\x0f_is_apple_watchB\x10\n" +
	"\x0e_is_white_listB\x12\n" +
	"\x10_is_local_iphone\"\xbf\x01\n" +
	"\x18UploadDeviceStepResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x12?\n" +
	"\vdevice_info\x18\x02 \x01(\v2\x19.api.user.SportDeviceInfoH\x01R\n" +
	"deviceInfo\x88\x01\x01B\x10\n" +
	"\x0e_base_responseB\x0e\n" +
	"\f_device_info\"\x86\x0f\n" +
	"\x1bGetBoundHardDevicesResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x12\x19\n" +
	"\x05count\x18\x02 \x01(\rH\x01R\x05count\x88\x01\x01\x12D\n" +
	"\x04list\x18\x05 \x03(\v20.api.user.GetBoundHardDevicesResponse.HardDeviceR\x04list\x12\x1d\n" +
	"\aversion\x18\x06 \x01(\x03H\x02R\aversion\x88\x01\x01\x12(\n" +
	"\rcontinue_flag\x18\a \x01(\x03H\x03R\fcontinueFlag\x88\x01\x01\x1a\xc0\f\n" +
	"\n" +
	"HardDevice\x12T\n" +
	"\x06device\x18\x01 \x01(\v27.api.user.GetBoundHardDevicesResponse.HardDevice.DeviceH\x00R\x06device\x88\x01\x01\x12]\n" +
	"\tattribute\x18\x02 \x01(\v2:.api.user.GetBoundHardDevicesResponse.HardDevice.AttributeH\x01R\tattribute\x88\x01\x01\x12\x17\n" +
	"\x04flag\x18\x03 \x01(\rH\x02R\x04flag\x88\x01\x01\x1aF\n" +
	"\x06Device\x12\x17\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x04type\x88\x01\x01\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tH\x01R\x02id\x88\x01\x01B\a\n" +
	"\x05_typeB\x05\n" +
	"\x03_id\x1a\xf9\t\n" +
	"\tAttribute\x12\"\n" +
	"\n" +
	"brand_name\x18\x01 \x01(\tH\x00R\tbrandName\x88\x01\x01\x12\x1e\n" +
	"\bauth_key\x18\x02 \x01(\tH\x01R\aauthKey\x88\x01\x01\x12\x15\n" +
	"\x03mac\x18\x03 \x01(\tH\x02R\x03mac\x88\x01\x01\x12\"\n" +
	"\n" +
	"conn_proto\x18\x04 \x01(\tH\x03R\tconnProto\x88\x01\x01\x12(\n" +
	"\rconn_strategy\x18\x05 \x01(\rH\x04R\fconnStrategy\x88\x01\x01\x12*\n" +
	"\x0eclose_strategy\x18\x06 \x01(\rH\x05R\rcloseStrategy\x88\x01\x01\x12%\n" +
	"\fmanu_mac_pos\x18\a \x01(\x05H\x06R\n" +
	"manuMacPos\x88\x01\x01\x12#\n" +
	"\vser_mac_pos\x18\b \x01(\x05H\aR\tserMacPos\x88\x01\x01\x128\n" +
	"\x15attribute_description\x18\t \x01(\tH\bR\x14attributeDescription\x88\x01\x01\x12\x19\n" +
	"\x05alias\x18\n" +
	" \x01(\tH\tR\x05alias\x88\x01\x01\x12\x1e\n" +
	"\bicon_url\x18\v \x01(\tH\n" +
	"R\aiconUrl\x88\x01\x01\x12\x1e\n" +
	"\bjump_url\x18\f \x01(\tH\vR\ajumpUrl\x88\x01\x01\x12&\n" +
	"\fdevice_title\x18\r \x01(\tH\fR\vdeviceTitle\x88\x01\x01\x122\n" +
	"\x12device_description\x18\x0e \x01(\tH\rR\x11deviceDescription\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\x0f \x01(\tH\x0eR\bcategory\x88\x01\x01\x12:\n" +
	"\x17device_type_main_device\x18\x10 \x01(\rH\x0fR\x14deviceTypeMainDevice\x88\x01\x01\x120\n" +
	"\x12is_enter_my_device\x18\x11 \x01(\rH\x10R\x0fisEnterMyDevice\x88\x01\x01\x123\n" +
	"\x13ble_simple_protocol\x18\x12 \x01(\x03H\x11R\x11bleSimpleProtocol\x88\x01\x01\x12\x1d\n" +
	"\aability\x18\x13 \x01(\tH\x12R\aability\x88\x01\x01\x12&\n" +
	"\fability_info\x18\x14 \x01(\tH\x13R\vabilityInfo\x88\x01\x01\x12(\n" +
	"\rserial_number\x18\x15 \x01(\tH\x14R\fserialNumber\x88\x01\x01\x12+\n" +
	"\x0fsub_device_list\x18\x16 \x01(\tH\x15R\rsubDeviceList\x88\x01\x01B\r\n" +
	"\v_brand_nameB\v\n" +
	"\t_auth_keyB\x06\n" +
	"\x04_macB\r\n" +
	"\v_conn_protoB\x10\n" +
	"\x0e_conn_strategyB\x11\n" +
	"\x0f_close_strategyB\x0f\n" +
	"\r_manu_mac_posB\x0e\n" +
	"\f_ser_mac_posB\x18\n" +
	"\x16_attribute_descriptionB\b\n" +
	"\x06_aliasB\v\n" +
	"\t_icon_urlB\v\n" +
	"\t_jump_urlB\x0f\n" +
	"\r_device_titleB\x15\n" +
	"\x13_device_descriptionB\v\n" +
	"\t_categoryB\x1a\n" +
	"\x18_device_type_main_deviceB\x15\n" +
	"\x13_is_enter_my_deviceB\x16\n" +
	"\x14_ble_simple_protocolB\n" +
	"\n" +
	"\b_abilityB\x0f\n" +
	"\r_ability_infoB\x10\n" +
	"\x0e_serial_numberB\x12\n" +
	"\x10_sub_device_listB\t\n" +
	"\a_deviceB\f\n" +
	"\n" +
	"_attributeB\a\n" +
	"\x05_flagB\x10\n" +
	"\x0e_base_responseB\b\n" +
	"\x06_countB\n" +
	"\n" +
	"\b_versionB\x10\n" +
	"\x0e_continue_flag\"\xb6\x02\n" +
	"\x0fGetCertResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x12:\n" +
	"\x04cert\x18\x02 \x01(\v2!.api.user.GetCertResponse.RSACertH\x01R\x04cert\x88\x01\x01\x12&\n" +
	"\fcert_version\x18\x03 \x01(\rH\x02R\vcertVersion\x88\x01\x01\x1aQ\n" +
	"\aRSACert\x12\x18\n" +
	"\x05key_n\x18\x01 \x01(\tH\x00R\x04keyN\x88\x01\x01\x12\x18\n" +
	"\x05key_e\x18\x02 \x01(\tH\x01R\x04keyE\x88\x01\x01B\b\n" +
	"\x06_key_nB\b\n" +
	"\x06_key_eB\x10\n" +
	"\x0e_base_responseB\a\n" +
	"\x05_certB\x0f\n" +
	"\r_cert_versionB1Z/github.com/sbgayhub/golem/host/api/user;userapib\x06proto3"

var (
	file_api_user_user_api_proto_rawDescOnce sync.Once
	file_api_user_user_api_proto_rawDescData []byte
)

func file_api_user_user_api_proto_rawDescGZIP() []byte {
	file_api_user_user_api_proto_rawDescOnce.Do(func() {
		file_api_user_user_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_user_api_proto_rawDesc), len(file_api_user_user_api_proto_rawDesc)))
	})
	return file_api_user_user_api_proto_rawDescData
}

var file_api_user_user_api_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_user_user_api_proto_goTypes = []any{
	(*GetProfileResponse)(nil),                               // 0: api.user.GetProfileResponse
	(*UploadAvatarResponse)(nil),                             // 1: api.user.UploadAvatarResponse
	(*GetQRCodeResponse)(nil),                                // 2: api.user.GetQRCodeResponse
	(*BindEmailResponse)(nil),                                // 3: api.user.BindEmailResponse
	(*SendVerifyEmailResponse)(nil),                          // 4: api.user.SendVerifyEmailResponse
	(*BindOpMobileResponse)(nil),                             // 5: api.user.BindOpMobileResponse
	(*SetPasswordResponse)(nil),                              // 6: api.user.SetPasswordResponse
	(*VerifyPasswordResponse)(nil),                           // 7: api.user.VerifyPasswordResponse
	(*GetSafetyInfoResponse)(nil),                            // 8: api.user.GetSafetyInfoResponse
	(*DeleteSafeDeviceResponse)(nil),                         // 9: api.user.DeleteSafeDeviceResponse
	(*GeneralSetResponse)(nil),                               // 10: api.user.GeneralSetResponse
	(*SportDeviceInfo)(nil),                                  // 11: api.user.SportDeviceInfo
	(*UploadDeviceStepResponse)(nil),                         // 12: api.user.UploadDeviceStepResponse
	(*GetBoundHardDevicesResponse)(nil),                      // 13: api.user.GetBoundHardDevicesResponse
	(*GetCertResponse)(nil),                                  // 14: api.user.GetCertResponse
	(*BindOpMobileResponse_SafeDeviceList)(nil),              // 15: api.user.BindOpMobileResponse.SafeDeviceList
	(*BindOpMobileResponse_ShowStyleKey)(nil),                // 16: api.user.BindOpMobileResponse.ShowStyleKey
	(*BindOpMobileResponse_SafeDeviceList_SafeDevice)(nil),   // 17: api.user.BindOpMobileResponse.SafeDeviceList.SafeDevice
	(*GetSafetyInfoResponse_SafetyDevice)(nil),               // 18: api.user.GetSafetyInfoResponse.SafetyDevice
	(*GetSafetyInfoResponse_SafetyInfo)(nil),                 // 19: api.user.GetSafetyInfoResponse.SafetyInfo
	(*GetBoundHardDevicesResponse_HardDevice)(nil),           // 20: api.user.GetBoundHardDevicesResponse.HardDevice
	(*GetBoundHardDevicesResponse_HardDevice_Device)(nil),    // 21: api.user.GetBoundHardDevicesResponse.HardDevice.Device
	(*GetBoundHardDevicesResponse_HardDevice_Attribute)(nil), // 22: api.user.GetBoundHardDevicesResponse.HardDevice.Attribute
	(*GetCertResponse_RSACert)(nil),                          // 23: api.user.GetCertResponse.RSACert
	(*base.BaseResponse)(nil),                                // 24: api.base.BaseResponse
	(*message.ModifyUserInfo)(nil),                           // 25: api.message.ModifyUserInfo
	(*message.UserInfoExtend)(nil),                           // 26: api.message.UserInfoExtend
	(*base.Buffer)(nil),                                      // 27: api.base.Buffer
	(*base.Hosts)(nil),                                       // 28: api.base.Hosts
	(*base.BuiltinIPList)(nil),                               // 29: api.base.BuiltinIPList
	(*base.NetworkControl)(nil),                              // 30: api.base.NetworkControl
	(*wrapperspb.StringValue)(nil),                           // 31: google.protobuf.StringValue
}
var file_api_user_user_api_proto_depIdxs = []int32{
	24, // 0: api.user.GetProfileResponse.base_response:type_name -> api.base.BaseResponse
	25, // 1: api.user.GetProfileResponse.user_info:type_name -> api.message.ModifyUserInfo
	26, // 2: api.user.GetProfileResponse.user_info_ext:type_name -> api.message.UserInfoExtend
	24, // 3: api.user.UploadAvatarResponse.base_response:type_name -> api.base.BaseResponse
	24, // 4: api.user.GetQRCodeResponse.base_response:type_name -> api.base.BaseResponse
	27, // 5: api.user.GetQRCodeResponse.qrcode_buffer:type_name -> api.base.Buffer
	24, // 6: api.user.BindEmailResponse.base_response:type_name -> api.base.BaseResponse
	24, // 7: api.user.SendVerifyEmailResponse.base_response:type_name -> api.base.BaseResponse
	24, // 8: api.user.BindOpMobileResponse.base_response:type_name -> api.base.BaseResponse
	28, // 9: api.user.BindOpMobileResponse.new_host_list:type_name -> api.base.Hosts
	29, // 10: api.user.BindOpMobileResponse.builtinIplist:type_name -> api.base.BuiltinIPList
	30, // 11: api.user.BindOpMobileResponse.network_control:type_name -> api.base.NetworkControl
	15, // 12: api.user.BindOpMobileResponse.safeDeviceList:type_name -> api.user.BindOpMobileResponse.SafeDeviceList
	16, // 13: api.user.BindOpMobileResponse.showStyle:type_name -> api.user.BindOpMobileResponse.ShowStyleKey
	24, // 14: api.user.SetPasswordResponse.base_response:type_name -> api.base.BaseResponse
	27, // 15: api.user.SetPasswordResponse.auto_auth_key:type_name -> api.base.Buffer
	24, // 16: api.user.VerifyPasswordResponse.base_response:type_name -> api.base.BaseResponse
	31, // 17: api.user.VerifyPasswordResponse.image_sid:type_name -> google.protobuf.StringValue
	27, // 18: api.user.VerifyPasswordResponse.image_buffer:type_name -> api.base.Buffer
	31, // 19: api.user.VerifyPasswordResponse.image_encrypt_key:type_name -> google.protobuf.StringValue
	27, // 20: api.user.VerifyPasswordResponse.a2_Key:type_name -> api.base.Buffer
	27, // 21: api.user.VerifyPasswordResponse.ksid:type_name -> api.base.Buffer
	27, // 22: api.user.VerifyPasswordResponse.wt_login_response_buffer:type_name -> api.base.Buffer
	24, // 23: api.user.GetSafetyInfoResponse.base_response:type_name -> api.base.BaseResponse
	19, // 24: api.user.GetSafetyInfoResponse.info:type_name -> api.user.GetSafetyInfoResponse.SafetyInfo
	24, // 25: api.user.DeleteSafeDeviceResponse.base_response:type_name -> api.base.BaseResponse
	24, // 26: api.user.GeneralSetResponse.base_response:type_name -> api.base.BaseResponse
	24, // 27: api.user.UploadDeviceStepResponse.base_response:type_name -> api.base.BaseResponse
	11, // 28: api.user.UploadDeviceStepResponse.device_info:type_name -> api.user.SportDeviceInfo
	24, // 29: api.user.GetBoundHardDevicesResponse.base_response:type_name -> api.base.BaseResponse
	20, // 30: api.user.GetBoundHardDevicesResponse.list:type_name -> api.user.GetBoundHardDevicesResponse.HardDevice
	24, // 31: api.user.GetCertResponse.base_response:type_name -> api.base.BaseResponse
	23, // 32: api.user.GetCertResponse.cert:type_name -> api.user.GetCertResponse.RSACert
	17, // 33: api.user.BindOpMobileResponse.SafeDeviceList.list:type_name -> api.user.BindOpMobileResponse.SafeDeviceList.SafeDevice
	18, // 34: api.user.GetSafetyInfoResponse.SafetyInfo.device_list:type_name -> api.user.GetSafetyInfoResponse.SafetyDevice
	21, // 35: api.user.GetBoundHardDevicesResponse.HardDevice.device:type_name -> api.user.GetBoundHardDevicesResponse.HardDevice.Device
	22, // 36: api.user.GetBoundHardDevicesResponse.HardDevice.attribute:type_name -> api.user.GetBoundHardDevicesResponse.HardDevice.Attribute
	37, // [37:37] is the sub-list for method output_type
	37, // [37:37] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_api_user_user_api_proto_init() }
func file_api_user_user_api_proto_init() {
	if File_api_user_user_api_proto != nil {
		return
	}
	file_api_user_user_api_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_user_user_api_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_user_user_api_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_user_user_api_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_user_user_api_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_user_user_api_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_user_user_api_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_user_user_api_proto_msgTypes[7].OneofWrappers = []any{}
	file_api_user_user_api_proto_msgTypes[8].OneofWrappers = []any{}
	file_api_user_user_api_proto_msgTypes[9].OneofWrappers = []any{}
	file_api_user_user_api_proto_msgTypes[10].OneofWrappers = []any{}
	file_api_user_user_api_proto_msgTypes[11].OneofWrappers = []any{}
	file_api_user_user_api_proto_msgTypes[12].OneofWrappers = []any{}
	file_api_user_user_api_proto_msgTypes[13].OneofWrappers = []any{}
	file_api_user_user_api_proto_msgTypes[14].OneofWrappers = []any{}
	file_api_user_user_api_proto_msgTypes[15].OneofWrappers = []any{}
	file_api_user_user_api_proto_msgTypes[16].OneofWrappers = []any{}
	file_api_user_user_api_proto_msgTypes[17].OneofWrappers = []any{}
	file_api_user_user_api_proto_msgTypes[18].OneofWrappers = []any{}
	file_api_user_user_api_proto_msgTypes[19].OneofWrappers = []any{}
	file_api_user_user_api_proto_msgTypes[20].OneofWrappers = []any{}
	file_api_user_user_api_proto_msgTypes[21].OneofWrappers = []any{}
	file_api_user_user_api_proto_msgTypes[22].OneofWrappers = []any{}
	file_api_user_user_api_proto_msgTypes[23].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_user_api_proto_rawDesc), len(file_api_user_user_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_user_user_api_proto_goTypes,
		DependencyIndexes: file_api_user_user_api_proto_depIdxs,
		MessageInfos:      file_api_user_user_api_proto_msgTypes,
	}.Build()
	File_api_user_user_api_proto = out.File
	file_api_user_user_api_proto_goTypes = nil
	file_api_user_user_api_proto_depIdxs = nil
}
