// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/payment/payment_api.proto

package paymentapi

import (
	base "github.com/sbgayhub/golem/host/api/base"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CGICommand 支付 CGI 命令（镜像 golem.payment.CGICommand）
type CGICommand int32

const (
	CGICommand_CGI_CMD_UNKNOWN              CGICommand = 0
	CGICommand_WEB_QUERY_CHECK_RECORD       CGICommand = 22
	CGICommand_PLATFORM_QUERY_CHECK_RECORD  CGICommand = 23
	CGICommand_WEB_QUERY_CHECK_RESULT       CGICommand = 24
	CGICommand_PLATFORM_QUERY_CHECK_RESULT  CGICommand = 25
	CGICommand_WEB_NOTIFY_CHECK_RESULT      CGICommand = 26
	CGICommand_PLATFORM_NOTIFY_CHECK_RESULT CGICommand = 27
	CGICommand_PLATFORM_QUERY_BZJ_INFO      CGICommand = 34
	CGICommand_QUERY_NEW_PARTNER_ID         CGICommand = 55
	CGICommand_QUERY_BIZ_CHECK_RESULT       CGICommand = 56
)

// Enum value maps for CGICommand.
var (
	CGICommand_name = map[int32]string{
		0:  "CGI_CMD_UNKNOWN",
		22: "WEB_QUERY_CHECK_RECORD",
		23: "PLATFORM_QUERY_CHECK_RECORD",
		24: "WEB_QUERY_CHECK_RESULT",
		25: "PLATFORM_QUERY_CHECK_RESULT",
		26: "WEB_NOTIFY_CHECK_RESULT",
		27: "PLATFORM_NOTIFY_CHECK_RESULT",
		34: "PLATFORM_QUERY_BZJ_INFO",
		55: "QUERY_NEW_PARTNER_ID",
		56: "QUERY_BIZ_CHECK_RESULT",
	}
	CGICommand_value = map[string]int32{
		"CGI_CMD_UNKNOWN":              0,
		"WEB_QUERY_CHECK_RECORD":       22,
		"PLATFORM_QUERY_CHECK_RECORD":  23,
		"WEB_QUERY_CHECK_RESULT":       24,
		"PLATFORM_QUERY_CHECK_RESULT":  25,
		"WEB_NOTIFY_CHECK_RESULT":      26,
		"PLATFORM_NOTIFY_CHECK_RESULT": 27,
		"PLATFORM_QUERY_BZJ_INFO":      34,
		"QUERY_NEW_PARTNER_ID":         55,
		"QUERY_BIZ_CHECK_RESULT":       56,
	}
)

func (x CGICommand) Enum() *CGICommand {
	p := new(CGICommand)
	*p = x
	return p
}

func (x CGICommand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CGICommand) Descriptor() protoreflect.EnumDescriptor {
	return file_api_payment_payment_api_proto_enumTypes[0].Descriptor()
}

func (CGICommand) Type() protoreflect.EnumType {
	return &file_api_payment_payment_api_proto_enumTypes[0]
}

func (x CGICommand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CGICommand.Descriptor instead.
func (CGICommand) EnumDescriptor() ([]byte, []int) {
	return file_api_payment_payment_api_proto_rawDescGZIP(), []int{0}
}

// TenPayResponse 腾讯支付响应（镜像 golem.payment.TenPayResponse）
type TenPayResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	BaseResponse  *base.BaseResponse      `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	Text          *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=text,proto3,oneof" json:"text,omitempty"`
	Code          *int32                  `protobuf:"varint,3,opt,name=code,proto3,oneof" json:"code,omitempty"`
	Message       *string                 `protobuf:"bytes,4,opt,name=message,proto3,oneof" json:"message,omitempty"`
	CgiCmd        *CGICommand             `protobuf:"varint,5,opt,name=cgi_cmd,json=cgiCmd,proto3,enum=api.payment.CGICommand,oneof" json:"cgi_cmd,omitempty"`
	ErrorType     *int32                  `protobuf:"varint,6,opt,name=error_type,json=errorType,proto3,oneof" json:"error_type,omitempty"`
	ErrorMessage  *string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenPayResponse) Reset() {
	*x = TenPayResponse{}
	mi := &file_api_payment_payment_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenPayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenPayResponse) ProtoMessage() {}

func (x *TenPayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_payment_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenPayResponse.ProtoReflect.Descriptor instead.
func (*TenPayResponse) Descriptor() ([]byte, []int) {
	return file_api_payment_payment_api_proto_rawDescGZIP(), []int{0}
}

func (x *TenPayResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *TenPayResponse) GetText() *wrapperspb.StringValue {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *TenPayResponse) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *TenPayResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *TenPayResponse) GetCgiCmd() CGICommand {
	if x != nil && x.CgiCmd != nil {
		return *x.CgiCmd
	}
	return CGICommand_CGI_CMD_UNKNOWN
}

func (x *TenPayResponse) GetErrorType() int32 {
	if x != nil && x.ErrorType != nil {
		return *x.ErrorType
	}
	return 0
}

func (x *TenPayResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

// HongBaoResponse 红包通用响应（镜像 golem.payment.HongBaoResponse）
type HongBaoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResponse  *base.BaseResponse     `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	Text          *base.Buffer           `protobuf:"bytes,2,opt,name=text,proto3,oneof" json:"text,omitempty"`
	Code          *int32                 `protobuf:"varint,3,opt,name=code,proto3,oneof" json:"code,omitempty"`
	Message       *string                `protobuf:"bytes,4,opt,name=message,proto3,oneof" json:"message,omitempty"`
	CgiCommand    *int32                 `protobuf:"varint,5,opt,name=cgi_command,json=cgiCommand,proto3,oneof" json:"cgi_command,omitempty"`
	ErrorType     *int32                 `protobuf:"varint,6,opt,name=error_type,json=errorType,proto3,oneof" json:"error_type,omitempty"`
	ErrorMessage  *string                `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HongBaoResponse) Reset() {
	*x = HongBaoResponse{}
	mi := &file_api_payment_payment_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HongBaoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HongBaoResponse) ProtoMessage() {}

func (x *HongBaoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_payment_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HongBaoResponse.ProtoReflect.Descriptor instead.
func (*HongBaoResponse) Descriptor() ([]byte, []int) {
	return file_api_payment_payment_api_proto_rawDescGZIP(), []int{1}
}

func (x *HongBaoResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *HongBaoResponse) GetText() *base.Buffer {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *HongBaoResponse) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *HongBaoResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *HongBaoResponse) GetCgiCommand() int32 {
	if x != nil && x.CgiCommand != nil {
		return *x.CgiCommand
	}
	return 0
}

func (x *HongBaoResponse) GetErrorType() int32 {
	if x != nil && x.ErrorType != nil {
		return *x.ErrorType
	}
	return 0
}

func (x *HongBaoResponse) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

// F2FQrcodeResponse F2F 支付二维码响应（镜像 golem.payment.F2FQrcodeResponse）
type F2FQrcodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResponse  *base.BaseResponse     `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	QrcodeUrl     *string                `protobuf:"bytes,2,opt,name=qrcode_url,json=qrcodeUrl,proto3,oneof" json:"qrcode_url,omitempty"`
	QrcodeData    *string                `protobuf:"bytes,3,opt,name=qrcode_data,json=qrcodeData,proto3,oneof" json:"qrcode_data,omitempty"`
	ExpireTime    *uint32                `protobuf:"varint,4,opt,name=expire_time,json=expireTime,proto3,oneof" json:"expire_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *F2FQrcodeResponse) Reset() {
	*x = F2FQrcodeResponse{}
	mi := &file_api_payment_payment_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *F2FQrcodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*F2FQrcodeResponse) ProtoMessage() {}

func (x *F2FQrcodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_payment_payment_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use F2FQrcodeResponse.ProtoReflect.Descriptor instead.
func (*F2FQrcodeResponse) Descriptor() ([]byte, []int) {
	return file_api_payment_payment_api_proto_rawDescGZIP(), []int{2}
}

func (x *F2FQrcodeResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *F2FQrcodeResponse) GetQrcodeUrl() string {
	if x != nil && x.QrcodeUrl != nil {
		return *x.QrcodeUrl
	}
	return ""
}

func (x *F2FQrcodeResponse) GetQrcodeData() string {
	if x != nil && x.QrcodeData != nil {
		return *x.QrcodeData
	}
	return ""
}

func (x *F2FQrcodeResponse) GetExpireTime() uint32 {
	if x != nil && x.ExpireTime != nil {
		return *x.ExpireTime
	}
	return 0
}

var File_api_payment_payment_api_proto protoreflect.FileDescriptor

const file_api_payment_payment_api_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/payment/payment_api.proto\x12\vapi.payment\x1a\x13api/base/base.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xa3\x03\n" +
	"\x0eTenPayResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x125\n" +
	"\x04text\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueH\x01R\x04text\x88\x01\x01\x12\x17\n" +
	"\x04code\x18\x03 \x01(\x05H\x02R\x04code\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x04 \x01(\tH\x03R\amessage\x88\x01\x01\x125\n" +
	"\acgi_cmd\x18\x05 \x01(\x0e2\x17.api.payment.CGICommandH\x04R\x06cgiCmd\x88\x01\x01\x12\"\n" +
	"\n" +
	"error_type\x18\x06 \x01(\x05H\x05R\terrorType\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\a \x01(\tH\x06R\ferrorMessage\x88\x01\x01B\x10\n" +
	"\x0e_base_responseB\a\n" +
	"\x05_textB\a\n" +
	"\x05_codeB\n" +
	"\n" +
	"\b_messageB\n" +
	"\n" +
	"\b_cgi_cmdB\r\n" +
	"\v_error_typeB\x10\n" +
	"\x0e_error_message\"\x8b\x03\n" +
	"\x0fHongBaoResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x12)\n" +
	"\x04text\x18\x02 \x01(\v2\x10.api.base.BufferH\x01R\x04text\x88\x01\x01\x12\x17\n" +
	"\x04code\x18\x03 \x01(\x05H\x02R\x04code\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x04 \x01(\tH\x03R\amessage\x88\x01\x01\x12$\n" +
	"\vcgi_command\x18\x05 \x01(\x05H\x04R\n" +
	"cgiCommand\x88\x01\x01\x12\"\n" +
	"\n" +
	"error_type\x18\x06 \x01(\x05H\x05R\terrorType\x88\x01\x01\x12(\n" +
	"\rerror_message\x18\a \x01(\tH\x06R\ferrorMessage\x88\x01\x01B\x10\n" +
	"\x0e_base_responseB\a\n" +
	"\x05_textB\a\n" +
	"\x05_codeB\n" +
	"\n" +
	"\b_messageB\x0e\n" +
	"\f_cgi_commandB\r\n" +
	"\v_error_typeB\x10\n" +
	"\x0e_error_message\"\x86\x02\n" +
	"\x11F2FQrcodeResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x12\"\n" +
	"\n" +
	"qrcode_url\x18\x02 \x01(\tH\x01R\tqrcodeUrl\x88\x01\x01\x12$\n" +
	"\vqrcode_data\x18\x03 \x01(\tH\x02R\n" +
	"qrcodeData\x88\x01\x01\x12$\n" +
	"\vexpire_time\x18\x04 \x01(\rH\x03R\n" +
	"expireTime\x88\x01\x01B\x10\n" +
	"\x0e_base_responseB\r\n" +
	"\v_qrcode_urlB\x0e\n" +
	"\f_qrcode_dataB\x0e\n" +
	"\f_expire_time*\xad\x02\n" +
	"\n" +
	"CGICommand\x12\x13\n" +
	"\x0fCGI_CMD_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16WEB_QUERY_CHECK_RECORD\x10\x16\x12\x1f\n" +
	"\x1bPLATFORM_QUERY_CHECK_RECORD\x10\x17\x12\x1a\n" +
	"\x16WEB_QUERY_CHECK_RESULT\x10\x18\x12\x1f\n" +
	"\x1bPLATFORM_QUERY_CHECK_RESULT\x10\x19\x12\x1b\n" +
	"\x17WEB_NOTIFY_CHECK_RESULT\x10\x1a\x12 \n" +
	"\x1cPLATFORM_NOTIFY_CHECK_RESULT\x10\x1b\x12\x1b\n" +
	"\x17PLATFORM_QUERY_BZJ_INFO\x10\"\x12\x18\n" +
	"\x14QUERY_NEW_PARTNER_ID\x107\x12\x1a\n" +
	"\x16QUERY_BIZ_CHECK_RESULT\x108B7Z5github.com/sbgayhub/golem/host/api/payment;paymentapib\x06proto3"

var (
	file_api_payment_payment_api_proto_rawDescOnce sync.Once
	file_api_payment_payment_api_proto_rawDescData []byte
)

func file_api_payment_payment_api_proto_rawDescGZIP() []byte {
	file_api_payment_payment_api_proto_rawDescOnce.Do(func() {
		file_api_payment_payment_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_payment_payment_api_proto_rawDesc), len(file_api_payment_payment_api_proto_rawDesc)))
	})
	return file_api_payment_payment_api_proto_rawDescData
}

var file_api_payment_payment_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_payment_payment_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_payment_payment_api_proto_goTypes = []any{
	(CGICommand)(0),                // 0: api.payment.CGICommand
	(*TenPayResponse)(nil),         // 1: api.payment.TenPayResponse
	(*HongBaoResponse)(nil),        // 2: api.payment.HongBaoResponse
	(*F2FQrcodeResponse)(nil),      // 3: api.payment.F2FQrcodeResponse
	(*base.BaseResponse)(nil),      // 4: api.base.BaseResponse
	(*wrapperspb.StringValue)(nil), // 5: google.protobuf.StringValue
	(*base.Buffer)(nil),            // 6: api.base.Buffer
}
var file_api_payment_payment_api_proto_depIdxs = []int32{
	4, // 0: api.payment.TenPayResponse.base_response:type_name -> api.base.BaseResponse
	5, // 1: api.payment.TenPayResponse.text:type_name -> google.protobuf.StringValue
	0, // 2: api.payment.TenPayResponse.cgi_cmd:type_name -> api.payment.CGICommand
	4, // 3: api.payment.HongBaoResponse.base_response:type_name -> api.base.BaseResponse
	6, // 4: api.payment.HongBaoResponse.text:type_name -> api.base.Buffer
	4, // 5: api.payment.F2FQrcodeResponse.base_response:type_name -> api.base.BaseResponse
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_payment_payment_api_proto_init() }
func file_api_payment_payment_api_proto_init() {
	if File_api_payment_payment_api_proto != nil {
		return
	}
	file_api_payment_payment_api_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_payment_payment_api_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_payment_payment_api_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_payment_payment_api_proto_rawDesc), len(file_api_payment_payment_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_payment_payment_api_proto_goTypes,
		DependencyIndexes: file_api_payment_payment_api_proto_depIdxs,
		EnumInfos:         file_api_payment_payment_api_proto_enumTypes,
		MessageInfos:      file_api_payment_payment_api_proto_msgTypes,
	}.Build()
	File_api_payment_payment_api_proto = out.File
	file_api_payment_payment_api_proto_goTypes = nil
	file_api_payment_payment_api_proto_depIdxs = nil
}
