version: '3'

vars:
  APP_NAME: golem
  VERSION: 0.1.1
  BUILD_DIR: build
  LDFLAGS: -s -w
  TAGS: web # 编译模式

tasks:
  build:
    desc: 构建当前平台二进制
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -tags {{.TAGS}} -ldflags "{{.LDFLAGS}}" -o {{.BUILD_DIR}}/{{.APP_NAME}}_{{OS}}_{{ARCH}}_{{.VERSION}}{{if eq OS "windows"}}.exe{{end}}

  buildall:
    desc: 构建所有平台二进制
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - GOOS=windows GOARCH=amd64 go build -tags {{.TAGS}} -ldflags "{{.LDFLAGS}}" -o {{.BUILD_DIR}}/{{.APP_NAME}}_{{.TAGS}}_windows_amd64_{{.VERSION}}.exe
      - GOOS=linux GOARCH=amd64 go build -tags {{.TAGS}} -ldflags "{{.LDFLAGS}}" -o {{.BUILD_DIR}}/{{.APP_NAME}}_{{.TAGS}}_linux_amd64_{{.VERSION}}
      - GOOS=linux GOARCH=arm64 go build -tags {{.TAGS}} -ldflags "{{.LDFLAGS}}" -o {{.BUILD_DIR}}/{{.APP_NAME}}_{{.TAGS}}_linux_arm64_{{.VERSION}}
      - GOOS=darwin GOARCH=amd64 go build -tags {{.TAGS}} -ldflags "{{.LDFLAGS}}" -o {{.BUILD_DIR}}/{{.APP_NAME}}_{{.TAGS}}_darwin_amd64_{{.VERSION}}
      - GOOS=darwin GOARCH=arm64 go build -tags {{.TAGS}} -ldflags "{{.LDFLAGS}}" -o {{.BUILD_DIR}}/{{.APP_NAME}}_{{.TAGS}}_darwin_arm64_{{.VERSION}}

  clean:
    desc: 清理构建产物
    cmds:
      - rm -rf {{.BUILD_DIR}}