// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/report/report_api.proto

package reportapi

import (
	base "github.com/sbgayhub/golem/host/api/base"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StatusNotifyRequest 状态通知请求（镜像 golem.report.StatusNotifyRequest）
type StatusNotifyRequest struct {
	state               protoimpl.MessageState                `protogen:"open.v1"`
	BaseRequest         *base.BaseRequest                     `protobuf:"bytes,1,opt,name=base_request,json=baseRequest,proto3,oneof" json:"base_request,omitempty"`
	Code                *uint32                               `protobuf:"varint,2,opt,name=code,proto3,oneof" json:"code,omitempty"`
	Sender              *string                               `protobuf:"bytes,3,opt,name=sender,proto3,oneof" json:"sender,omitempty"`
	Receiver            *string                               `protobuf:"bytes,4,opt,name=receiver,proto3,oneof" json:"receiver,omitempty"`
	ClientMsgId         *string                               `protobuf:"bytes,5,opt,name=client_msg_id,json=clientMsgId,proto3,oneof" json:"client_msg_id,omitempty"`
	UnreadChatListCount *uint32                               `protobuf:"varint,6,opt,name=unread_chat_list_count,json=unreadChatListCount,proto3,oneof" json:"unread_chat_list_count,omitempty"`
	UnreadChatList      []*StatusNotifyRequest_UnreadChat     `protobuf:"bytes,7,rep,name=unread_chat_list,json=unreadChatList,proto3" json:"unread_chat_list,omitempty"`
	Function            *StatusNotifyRequest_UnreadFunction   `protobuf:"bytes,8,opt,name=function,proto3,oneof" json:"function,omitempty"`
	UnreadFunctionCount *uint32                               `protobuf:"varint,9,opt,name=unread_function_count,json=unreadFunctionCount,proto3,oneof" json:"unread_function_count,omitempty"`
	UnreadFunctionList  []*StatusNotifyRequest_UnreadFunction `protobuf:"bytes,10,rep,name=unread_function_list,json=unreadFunctionList,proto3" json:"unread_function_list,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StatusNotifyRequest) Reset() {
	*x = StatusNotifyRequest{}
	mi := &file_api_report_report_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusNotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusNotifyRequest) ProtoMessage() {}

func (x *StatusNotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_report_report_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusNotifyRequest.ProtoReflect.Descriptor instead.
func (*StatusNotifyRequest) Descriptor() ([]byte, []int) {
	return file_api_report_report_api_proto_rawDescGZIP(), []int{0}
}

func (x *StatusNotifyRequest) GetBaseRequest() *base.BaseRequest {
	if x != nil {
		return x.BaseRequest
	}
	return nil
}

func (x *StatusNotifyRequest) GetCode() uint32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *StatusNotifyRequest) GetSender() string {
	if x != nil && x.Sender != nil {
		return *x.Sender
	}
	return ""
}

func (x *StatusNotifyRequest) GetReceiver() string {
	if x != nil && x.Receiver != nil {
		return *x.Receiver
	}
	return ""
}

func (x *StatusNotifyRequest) GetClientMsgId() string {
	if x != nil && x.ClientMsgId != nil {
		return *x.ClientMsgId
	}
	return ""
}

func (x *StatusNotifyRequest) GetUnreadChatListCount() uint32 {
	if x != nil && x.UnreadChatListCount != nil {
		return *x.UnreadChatListCount
	}
	return 0
}

func (x *StatusNotifyRequest) GetUnreadChatList() []*StatusNotifyRequest_UnreadChat {
	if x != nil {
		return x.UnreadChatList
	}
	return nil
}

func (x *StatusNotifyRequest) GetFunction() *StatusNotifyRequest_UnreadFunction {
	if x != nil {
		return x.Function
	}
	return nil
}

func (x *StatusNotifyRequest) GetUnreadFunctionCount() uint32 {
	if x != nil && x.UnreadFunctionCount != nil {
		return *x.UnreadFunctionCount
	}
	return 0
}

func (x *StatusNotifyRequest) GetUnreadFunctionList() []*StatusNotifyRequest_UnreadFunction {
	if x != nil {
		return x.UnreadFunctionList
	}
	return nil
}

// StatusNotifyResponse 状态通知响应（镜像 golem.report.StatusNotifyResponse）
type StatusNotifyResponse struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	BaseResponse     *base.BaseResponse        `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	MsgId            *uint32                   `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3,oneof" json:"msg_id,omitempty"`
	NewId            *uint64                   `protobuf:"varint,3,opt,name=new_id,json=newId,proto3,oneof" json:"new_id,omitempty"`
	ChatContactCount *uint32                   `protobuf:"varint,4,opt,name=chat_contact_count,json=chatContactCount,proto3,oneof" json:"chat_contact_count,omitempty"`
	ChatContactList  []*wrapperspb.StringValue `protobuf:"bytes,5,rep,name=chat_contact_list,json=chatContactList,proto3" json:"chat_contact_list,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatusNotifyResponse) Reset() {
	*x = StatusNotifyResponse{}
	mi := &file_api_report_report_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusNotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusNotifyResponse) ProtoMessage() {}

func (x *StatusNotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_report_report_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusNotifyResponse.ProtoReflect.Descriptor instead.
func (*StatusNotifyResponse) Descriptor() ([]byte, []int) {
	return file_api_report_report_api_proto_rawDescGZIP(), []int{1}
}

func (x *StatusNotifyResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *StatusNotifyResponse) GetMsgId() uint32 {
	if x != nil && x.MsgId != nil {
		return *x.MsgId
	}
	return 0
}

func (x *StatusNotifyResponse) GetNewId() uint64 {
	if x != nil && x.NewId != nil {
		return *x.NewId
	}
	return 0
}

func (x *StatusNotifyResponse) GetChatContactCount() uint32 {
	if x != nil && x.ChatContactCount != nil {
		return *x.ChatContactCount
	}
	return 0
}

func (x *StatusNotifyResponse) GetChatContactList() []*wrapperspb.StringValue {
	if x != nil {
		return x.ChatContactList
	}
	return nil
}

// UnreadChat 未读会话信息（镜像 golem.report.StatusNotifyRequest.UnreadChat）
type StatusNotifyRequest_UnreadChat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      *string                `protobuf:"bytes,1,opt,name=username,proto3,oneof" json:"username,omitempty"`
	LastReadTime  *uint32                `protobuf:"varint,2,opt,name=last_read_time,json=lastReadTime,proto3,oneof" json:"last_read_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusNotifyRequest_UnreadChat) Reset() {
	*x = StatusNotifyRequest_UnreadChat{}
	mi := &file_api_report_report_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusNotifyRequest_UnreadChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusNotifyRequest_UnreadChat) ProtoMessage() {}

func (x *StatusNotifyRequest_UnreadChat) ProtoReflect() protoreflect.Message {
	mi := &file_api_report_report_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusNotifyRequest_UnreadChat.ProtoReflect.Descriptor instead.
func (*StatusNotifyRequest_UnreadChat) Descriptor() ([]byte, []int) {
	return file_api_report_report_api_proto_rawDescGZIP(), []int{0, 0}
}

func (x *StatusNotifyRequest_UnreadChat) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *StatusNotifyRequest_UnreadChat) GetLastReadTime() uint32 {
	if x != nil && x.LastReadTime != nil {
		return *x.LastReadTime
	}
	return 0
}

// UnreadFunction 未读功能项（镜像 golem.report.StatusNotifyRequest.UnreadFunction）
type StatusNotifyRequest_UnreadFunction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Arg           *string                `protobuf:"bytes,2,opt,name=arg,proto3,oneof" json:"arg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusNotifyRequest_UnreadFunction) Reset() {
	*x = StatusNotifyRequest_UnreadFunction{}
	mi := &file_api_report_report_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusNotifyRequest_UnreadFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusNotifyRequest_UnreadFunction) ProtoMessage() {}

func (x *StatusNotifyRequest_UnreadFunction) ProtoReflect() protoreflect.Message {
	mi := &file_api_report_report_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusNotifyRequest_UnreadFunction.ProtoReflect.Descriptor instead.
func (*StatusNotifyRequest_UnreadFunction) Descriptor() ([]byte, []int) {
	return file_api_report_report_api_proto_rawDescGZIP(), []int{0, 1}
}

func (x *StatusNotifyRequest_UnreadFunction) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *StatusNotifyRequest_UnreadFunction) GetArg() string {
	if x != nil && x.Arg != nil {
		return *x.Arg
	}
	return ""
}

var File_api_report_report_api_proto protoreflect.FileDescriptor

const file_api_report_report_api_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/report/report_api.proto\x12\n" +
	"api.report\x1a\x13api/base/base.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xa3\a\n" +
	"\x13StatusNotifyRequest\x12=\n" +
	"\fbase_request\x18\x01 \x01(\v2\x15.api.base.BaseRequestH\x00R\vbaseRequest\x88\x01\x01\x12\x17\n" +
	"\x04code\x18\x02 \x01(\rH\x01R\x04code\x88\x01\x01\x12\x1b\n" +
	"\x06sender\x18\x03 \x01(\tH\x02R\x06sender\x88\x01\x01\x12\x1f\n" +
	"\breceiver\x18\x04 \x01(\tH\x03R\breceiver\x88\x01\x01\x12'\n" +
	"\rclient_msg_id\x18\x05 \x01(\tH\x04R\vclientMsgId\x88\x01\x01\x128\n" +
	"\x16unread_chat_list_count\x18\x06 \x01(\rH\x05R\x13unreadChatListCount\x88\x01\x01\x12T\n" +
	"\x10unread_chat_list\x18\a \x03(\v2*.api.report.StatusNotifyRequest.UnreadChatR\x0eunreadChatList\x12O\n" +
	"\bfunction\x18\b \x01(\v2..api.report.StatusNotifyRequest.UnreadFunctionH\x06R\bfunction\x88\x01\x01\x127\n" +
	"\x15unread_function_count\x18\t \x01(\rH\aR\x13unreadFunctionCount\x88\x01\x01\x12`\n" +
	"\x14unread_function_list\x18\n" +
	" \x03(\v2..api.report.StatusNotifyRequest.UnreadFunctionR\x12unreadFunctionList\x1ax\n" +
	"\n" +
	"UnreadChat\x12\x1f\n" +
	"\busername\x18\x01 \x01(\tH\x00R\busername\x88\x01\x01\x12)\n" +
	"\x0elast_read_time\x18\x02 \x01(\rH\x01R\flastReadTime\x88\x01\x01B\v\n" +
	"\t_usernameB\x11\n" +
	"\x0f_last_read_time\x1aQ\n" +
	"\x0eUnreadFunction\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x15\n" +
	"\x03arg\x18\x02 \x01(\tH\x01R\x03arg\x88\x01\x01B\a\n" +
	"\x05_nameB\x06\n" +
	"\x04_argB\x0f\n" +
	"\r_base_requestB\a\n" +
	"\x05_codeB\t\n" +
	"\a_senderB\v\n" +
	"\t_receiverB\x10\n" +
	"\x0e_client_msg_idB\x19\n" +
	"\x17_unread_chat_list_countB\v\n" +
	"\t_functionB\x18\n" +
	"\x16_unread_function_count\"\xcc\x02\n" +
	"\x14StatusNotifyResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x12\x1a\n" +
	"\x06msg_id\x18\x02 \x01(\rH\x01R\x05msgId\x88\x01\x01\x12\x1a\n" +
	"\x06new_id\x18\x03 \x01(\x04H\x02R\x05newId\x88\x01\x01\x121\n" +
	"\x12chat_contact_count\x18\x04 \x01(\rH\x03R\x10chatContactCount\x88\x01\x01\x12H\n" +
	"\x11chat_contact_list\x18\x05 \x03(\v2\x1c.google.protobuf.StringValueR\x0fchatContactListB\x10\n" +
	"\x0e_base_responseB\t\n" +
	"\a_msg_idB\t\n" +
	"\a_new_idB\x15\n" +
	"\x13_chat_contact_countB5Z3github.com/sbgayhub/golem/host/api/report;reportapib\x06proto3"

var (
	file_api_report_report_api_proto_rawDescOnce sync.Once
	file_api_report_report_api_proto_rawDescData []byte
)

func file_api_report_report_api_proto_rawDescGZIP() []byte {
	file_api_report_report_api_proto_rawDescOnce.Do(func() {
		file_api_report_report_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_report_report_api_proto_rawDesc), len(file_api_report_report_api_proto_rawDesc)))
	})
	return file_api_report_report_api_proto_rawDescData
}

var file_api_report_report_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_report_report_api_proto_goTypes = []any{
	(*StatusNotifyRequest)(nil),                // 0: api.report.StatusNotifyRequest
	(*StatusNotifyResponse)(nil),               // 1: api.report.StatusNotifyResponse
	(*StatusNotifyRequest_UnreadChat)(nil),     // 2: api.report.StatusNotifyRequest.UnreadChat
	(*StatusNotifyRequest_UnreadFunction)(nil), // 3: api.report.StatusNotifyRequest.UnreadFunction
	(*base.BaseRequest)(nil),                   // 4: api.base.BaseRequest
	(*base.BaseResponse)(nil),                  // 5: api.base.BaseResponse
	(*wrapperspb.StringValue)(nil),             // 6: google.protobuf.StringValue
}
var file_api_report_report_api_proto_depIdxs = []int32{
	4, // 0: api.report.StatusNotifyRequest.base_request:type_name -> api.base.BaseRequest
	2, // 1: api.report.StatusNotifyRequest.unread_chat_list:type_name -> api.report.StatusNotifyRequest.UnreadChat
	3, // 2: api.report.StatusNotifyRequest.function:type_name -> api.report.StatusNotifyRequest.UnreadFunction
	3, // 3: api.report.StatusNotifyRequest.unread_function_list:type_name -> api.report.StatusNotifyRequest.UnreadFunction
	5, // 4: api.report.StatusNotifyResponse.base_response:type_name -> api.base.BaseResponse
	6, // 5: api.report.StatusNotifyResponse.chat_contact_list:type_name -> google.protobuf.StringValue
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_report_report_api_proto_init() }
func file_api_report_report_api_proto_init() {
	if File_api_report_report_api_proto != nil {
		return
	}
	file_api_report_report_api_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_report_report_api_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_report_report_api_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_report_report_api_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_report_report_api_proto_rawDesc), len(file_api_report_report_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_report_report_api_proto_goTypes,
		DependencyIndexes: file_api_report_report_api_proto_depIdxs,
		MessageInfos:      file_api_report_report_api_proto_msgTypes,
	}.Build()
	File_api_report_report_api_proto = out.File
	file_api_report_report_api_proto_goTypes = nil
	file_api_report_report_api_proto_depIdxs = nil
}
