// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/moments/moments_api.proto

package momentsapi

import (
	base "github.com/sbgayhub/golem/host/api/base"
	message "github.com/sbgayhub/golem/host/api/message"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TwitterInfo Twitter 信息（镜像 golem.moments.TwitterInfo）
type TwitterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *string                `protobuf:"bytes,1,opt,name=token,proto3,oneof" json:"token,omitempty"`
	Secret        *string                `protobuf:"bytes,2,opt,name=secret,proto3,oneof" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwitterInfo) Reset() {
	*x = TwitterInfo{}
	mi := &file_api_moments_moments_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwitterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwitterInfo) ProtoMessage() {}

func (x *TwitterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_moments_moments_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwitterInfo.ProtoReflect.Descriptor instead.
func (*TwitterInfo) Descriptor() ([]byte, []int) {
	return file_api_moments_moments_api_proto_rawDescGZIP(), []int{0}
}

func (x *TwitterInfo) GetToken() string {
	if x != nil && x.Token != nil {
		return *x.Token
	}
	return ""
}

func (x *TwitterInfo) GetSecret() string {
	if x != nil && x.Secret != nil {
		return *x.Secret
	}
	return ""
}

// BufferUrl 朋友圈缓冲区 URL（镜像 golem.moments.BufferUrl）
type BufferUrl struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           *string                `protobuf:"bytes,1,opt,name=url,proto3,oneof" json:"url,omitempty"`
	Type          *uint32                `protobuf:"varint,2,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Size          *uint32                `protobuf:"varint,3,opt,name=size,proto3,oneof" json:"size,omitempty"`
	Md5           *string                `protobuf:"bytes,4,opt,name=md5,proto3,oneof" json:"md5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BufferUrl) Reset() {
	*x = BufferUrl{}
	mi := &file_api_moments_moments_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BufferUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BufferUrl) ProtoMessage() {}

func (x *BufferUrl) ProtoReflect() protoreflect.Message {
	mi := &file_api_moments_moments_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BufferUrl.ProtoReflect.Descriptor instead.
func (*BufferUrl) Descriptor() ([]byte, []int) {
	return file_api_moments_moments_api_proto_rawDescGZIP(), []int{1}
}

func (x *BufferUrl) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *BufferUrl) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *BufferUrl) GetSize() uint32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *BufferUrl) GetMd5() string {
	if x != nil && x.Md5 != nil {
		return *x.Md5
	}
	return ""
}

// ServerConfig 朋友圈服务器配置（镜像 golem.moments.ServerConfig）
type ServerConfig struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PostMentionLimit      *int32                 `protobuf:"varint,1,opt,name=post_mention_limit,json=postMentionLimit,proto3,oneof" json:"post_mention_limit,omitempty"`
	CopyAndPasteWordLimit *int32                 `protobuf:"varint,2,opt,name=copy_and_paste_word_limit,json=copyAndPasteWordLimit,proto3,oneof" json:"copy_and_paste_word_limit,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_api_moments_moments_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_moments_moments_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_api_moments_moments_api_proto_rawDescGZIP(), []int{2}
}

func (x *ServerConfig) GetPostMentionLimit() int32 {
	if x != nil && x.PostMentionLimit != nil {
		return *x.PostMentionLimit
	}
	return 0
}

func (x *ServerConfig) GetCopyAndPasteWordLimit() int32 {
	if x != nil && x.CopyAndPasteWordLimit != nil {
		return *x.CopyAndPasteWordLimit
	}
	return 0
}

// ADObject 广告对象（镜像 golem.moments.ADObject）
type ADObject struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Object        *message.MomentsObject  `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	AdXml         *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=ad_xml,json=adXml,proto3,oneof" json:"ad_xml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ADObject) Reset() {
	*x = ADObject{}
	mi := &file_api_moments_moments_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ADObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ADObject) ProtoMessage() {}

func (x *ADObject) ProtoReflect() protoreflect.Message {
	mi := &file_api_moments_moments_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ADObject.ProtoReflect.Descriptor instead.
func (*ADObject) Descriptor() ([]byte, []int) {
	return file_api_moments_moments_api_proto_rawDescGZIP(), []int{3}
}

func (x *ADObject) GetObject() *message.MomentsObject {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *ADObject) GetAdXml() *wrapperspb.StringValue {
	if x != nil {
		return x.AdXml
	}
	return nil
}

// RemindFriendsInfo 提醒好友信息（镜像 golem.moments.RemindFriendsInfo）
type RemindFriendsInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AdchatroomId   *uint64                `protobuf:"varint,1,opt,name=adchatroom_id,json=adchatroomId,proto3,oneof" json:"adchatroom_id,omitempty"`
	SourceInfo     *base.Buffer           `protobuf:"bytes,2,opt,name=source_info,json=sourceInfo,proto3,oneof" json:"source_info,omitempty"`
	SelfInfo       *base.Buffer           `protobuf:"bytes,3,opt,name=self_info,json=selfInfo,proto3,oneof" json:"self_info,omitempty"`
	PaidInfo       *base.Buffer           `protobuf:"bytes,4,opt,name=paid_info,json=paidInfo,proto3,oneof" json:"paid_info,omitempty"`
	ExtraInfo      *base.Buffer           `protobuf:"bytes,5,opt,name=extra_info,json=extraInfo,proto3,oneof" json:"extra_info,omitempty"`
	AdchatroomId64 *uint64                `protobuf:"varint,6,opt,name=adchatroom_id64,json=adchatroomId64,proto3,oneof" json:"adchatroom_id64,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemindFriendsInfo) Reset() {
	*x = RemindFriendsInfo{}
	mi := &file_api_moments_moments_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemindFriendsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemindFriendsInfo) ProtoMessage() {}

func (x *RemindFriendsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_moments_moments_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemindFriendsInfo.ProtoReflect.Descriptor instead.
func (*RemindFriendsInfo) Descriptor() ([]byte, []int) {
	return file_api_moments_moments_api_proto_rawDescGZIP(), []int{4}
}

func (x *RemindFriendsInfo) GetAdchatroomId() uint64 {
	if x != nil && x.AdchatroomId != nil {
		return *x.AdchatroomId
	}
	return 0
}

func (x *RemindFriendsInfo) GetSourceInfo() *base.Buffer {
	if x != nil {
		return x.SourceInfo
	}
	return nil
}

func (x *RemindFriendsInfo) GetSelfInfo() *base.Buffer {
	if x != nil {
		return x.SelfInfo
	}
	return nil
}

func (x *RemindFriendsInfo) GetPaidInfo() *base.Buffer {
	if x != nil {
		return x.PaidInfo
	}
	return nil
}

func (x *RemindFriendsInfo) GetExtraInfo() *base.Buffer {
	if x != nil {
		return x.ExtraInfo
	}
	return nil
}

func (x *RemindFriendsInfo) GetAdchatroomId64() uint64 {
	if x != nil && x.AdchatroomId64 != nil {
		return *x.AdchatroomId64
	}
	return 0
}

// PostResponse 发布朋友圈响应（镜像 golem.moments.PostResponse）
type PostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResponse  *base.BaseResponse     `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	Object        *message.MomentsObject `protobuf:"bytes,2,opt,name=object,proto3,oneof" json:"object,omitempty"`
	SpamTips      *string                `protobuf:"bytes,3,opt,name=spam_tips,json=spamTips,proto3,oneof" json:"spam_tips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostResponse) Reset() {
	*x = PostResponse{}
	mi := &file_api_moments_moments_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResponse) ProtoMessage() {}

func (x *PostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_moments_moments_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResponse.ProtoReflect.Descriptor instead.
func (*PostResponse) Descriptor() ([]byte, []int) {
	return file_api_moments_moments_api_proto_rawDescGZIP(), []int{5}
}

func (x *PostResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *PostResponse) GetObject() *message.MomentsObject {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *PostResponse) GetSpamTips() string {
	if x != nil && x.SpamTips != nil {
		return *x.SpamTips
	}
	return ""
}

// OperateResponse 朋友圈对象操作响应（镜像 golem.moments.OperateResponse）
type OperateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResponse  *base.BaseResponse     `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	Count         *uint32                `protobuf:"varint,2,opt,name=count,proto3,oneof" json:"count,omitempty"`
	List          []int32                `protobuf:"varint,3,rep,packed,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperateResponse) Reset() {
	*x = OperateResponse{}
	mi := &file_api_moments_moments_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateResponse) ProtoMessage() {}

func (x *OperateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_moments_moments_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateResponse.ProtoReflect.Descriptor instead.
func (*OperateResponse) Descriptor() ([]byte, []int) {
	return file_api_moments_moments_api_proto_rawDescGZIP(), []int{6}
}

func (x *OperateResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *OperateResponse) GetCount() uint32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *OperateResponse) GetList() []int32 {
	if x != nil {
		return x.List
	}
	return nil
}

// CommentResponse 朋友圈评论响应（镜像 golem.moments.CommentResponse）
type CommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResponse  *base.BaseResponse     `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	Object        *message.MomentsObject `protobuf:"bytes,2,opt,name=object,proto3,oneof" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentResponse) Reset() {
	*x = CommentResponse{}
	mi := &file_api_moments_moments_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentResponse) ProtoMessage() {}

func (x *CommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_moments_moments_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentResponse.ProtoReflect.Descriptor instead.
func (*CommentResponse) Descriptor() ([]byte, []int) {
	return file_api_moments_moments_api_proto_rawDescGZIP(), []int{7}
}

func (x *CommentResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *CommentResponse) GetObject() *message.MomentsObject {
	if x != nil {
		return x.Object
	}
	return nil
}

// UploadResponse 朋友圈上传响应（镜像 golem.moments.UploadResponse）
type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResponse  *base.BaseResponse     `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	Offset        *uint32                `protobuf:"varint,2,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	Size          *uint32                `protobuf:"varint,3,opt,name=size,proto3,oneof" json:"size,omitempty"`
	ClientId      *string                `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3,oneof" json:"client_id,omitempty"`
	BufferUrl     *BufferUrl             `protobuf:"bytes,5,opt,name=buffer_url,json=bufferUrl,proto3,oneof" json:"buffer_url,omitempty"`
	ThumbUrlCount *uint32                `protobuf:"varint,6,opt,name=thumb_url_count,json=thumbUrlCount,proto3,oneof" json:"thumb_url_count,omitempty"`
	ThumbUrlList  []*BufferUrl           `protobuf:"bytes,7,rep,name=thumb_url_list,json=thumbUrlList,proto3" json:"thumb_url_list,omitempty"`
	Id            *uint64                `protobuf:"varint,8,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Type          *uint32                `protobuf:"varint,9,opt,name=type,proto3,oneof" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_api_moments_moments_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_moments_moments_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_api_moments_moments_api_proto_rawDescGZIP(), []int{8}
}

func (x *UploadResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *UploadResponse) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *UploadResponse) GetSize() uint32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *UploadResponse) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *UploadResponse) GetBufferUrl() *BufferUrl {
	if x != nil {
		return x.BufferUrl
	}
	return nil
}

func (x *UploadResponse) GetThumbUrlCount() uint32 {
	if x != nil && x.ThumbUrlCount != nil {
		return *x.ThumbUrlCount
	}
	return 0
}

func (x *UploadResponse) GetThumbUrlList() []*BufferUrl {
	if x != nil {
		return x.ThumbUrlList
	}
	return nil
}

func (x *UploadResponse) GetId() uint64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *UploadResponse) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

// TimelineResponse 朋友圈时间线响应（镜像 golem.moments.TimelineResponse）
type TimelineResponse struct {
	state                 protoimpl.MessageState        `protogen:"open.v1"`
	BaseResponse          *base.BaseResponse            `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	FirstPageMd5          *string                       `protobuf:"bytes,2,opt,name=first_page_md5,json=firstPageMd5,proto3,oneof" json:"first_page_md5,omitempty"`
	ObjectCount           *uint32                       `protobuf:"varint,3,opt,name=object_count,json=objectCount,proto3,oneof" json:"object_count,omitempty"`
	ObjectList            []*message.MomentsObject      `protobuf:"bytes,4,rep,name=object_list,json=objectList,proto3" json:"object_list,omitempty"`
	NewRequestTime        *uint32                       `protobuf:"varint,5,opt,name=new_request_time,json=newRequestTime,proto3,oneof" json:"new_request_time,omitempty"`
	ObjectCountForSameMd5 *uint32                       `protobuf:"varint,6,opt,name=object_count_for_same_md5,json=objectCountForSameMd5,proto3,oneof" json:"object_count_for_same_md5,omitempty"`
	ControlFlag           *uint32                       `protobuf:"varint,7,opt,name=control_flag,json=controlFlag,proto3,oneof" json:"control_flag,omitempty"`
	ServerConfig          *ServerConfig                 `protobuf:"bytes,8,opt,name=server_config,json=serverConfig,proto3,oneof" json:"server_config,omitempty"`
	AdvertiseCount        *uint32                       `protobuf:"varint,9,opt,name=advertise_count,json=advertiseCount,proto3,oneof" json:"advertise_count,omitempty"`
	AdvertiseList         []*TimelineResponse_Advertise `protobuf:"bytes,10,rep,name=advertise_list,json=advertiseList,proto3" json:"advertise_list,omitempty"`
	Session               *base.Buffer                  `protobuf:"bytes,11,opt,name=session,proto3,oneof" json:"session,omitempty"`
	RecommendCount        *uint32                       `protobuf:"varint,12,opt,name=recommend_count,json=recommendCount,proto3,oneof" json:"recommend_count,omitempty"`
	RecommendList         []*TimelineResponse_Recommend `protobuf:"bytes,13,rep,name=recommend_list,json=recommendList,proto3" json:"recommend_list,omitempty"`
	DeleteAdvertiseCount  *uint32                       `protobuf:"varint,14,opt,name=delete_advertise_count,json=deleteAdvertiseCount,proto3,oneof" json:"delete_advertise_count,omitempty"`
	DeleteAdvertiseList   []*wrapperspb.UInt64Value     `protobuf:"bytes,15,rep,name=delete_advertise_list,json=deleteAdvertiseList,proto3" json:"delete_advertise_list,omitempty"`
	UnreadCount           *uint32                       `protobuf:"varint,16,opt,name=unread_count,json=unreadCount,proto3,oneof" json:"unread_count,omitempty"`
	UnreadList            []uint64                      `protobuf:"varint,17,rep,packed,name=unread_list,json=unreadList,proto3" json:"unread_list,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TimelineResponse) Reset() {
	*x = TimelineResponse{}
	mi := &file_api_moments_moments_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineResponse) ProtoMessage() {}

func (x *TimelineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_moments_moments_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineResponse.ProtoReflect.Descriptor instead.
func (*TimelineResponse) Descriptor() ([]byte, []int) {
	return file_api_moments_moments_api_proto_rawDescGZIP(), []int{9}
}

func (x *TimelineResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *TimelineResponse) GetFirstPageMd5() string {
	if x != nil && x.FirstPageMd5 != nil {
		return *x.FirstPageMd5
	}
	return ""
}

func (x *TimelineResponse) GetObjectCount() uint32 {
	if x != nil && x.ObjectCount != nil {
		return *x.ObjectCount
	}
	return 0
}

func (x *TimelineResponse) GetObjectList() []*message.MomentsObject {
	if x != nil {
		return x.ObjectList
	}
	return nil
}

func (x *TimelineResponse) GetNewRequestTime() uint32 {
	if x != nil && x.NewRequestTime != nil {
		return *x.NewRequestTime
	}
	return 0
}

func (x *TimelineResponse) GetObjectCountForSameMd5() uint32 {
	if x != nil && x.ObjectCountForSameMd5 != nil {
		return *x.ObjectCountForSameMd5
	}
	return 0
}

func (x *TimelineResponse) GetControlFlag() uint32 {
	if x != nil && x.ControlFlag != nil {
		return *x.ControlFlag
	}
	return 0
}

func (x *TimelineResponse) GetServerConfig() *ServerConfig {
	if x != nil {
		return x.ServerConfig
	}
	return nil
}

func (x *TimelineResponse) GetAdvertiseCount() uint32 {
	if x != nil && x.AdvertiseCount != nil {
		return *x.AdvertiseCount
	}
	return 0
}

func (x *TimelineResponse) GetAdvertiseList() []*TimelineResponse_Advertise {
	if x != nil {
		return x.AdvertiseList
	}
	return nil
}

func (x *TimelineResponse) GetSession() *base.Buffer {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *TimelineResponse) GetRecommendCount() uint32 {
	if x != nil && x.RecommendCount != nil {
		return *x.RecommendCount
	}
	return 0
}

func (x *TimelineResponse) GetRecommendList() []*TimelineResponse_Recommend {
	if x != nil {
		return x.RecommendList
	}
	return nil
}

func (x *TimelineResponse) GetDeleteAdvertiseCount() uint32 {
	if x != nil && x.DeleteAdvertiseCount != nil {
		return *x.DeleteAdvertiseCount
	}
	return 0
}

func (x *TimelineResponse) GetDeleteAdvertiseList() []*wrapperspb.UInt64Value {
	if x != nil {
		return x.DeleteAdvertiseList
	}
	return nil
}

func (x *TimelineResponse) GetUnreadCount() uint32 {
	if x != nil && x.UnreadCount != nil {
		return *x.UnreadCount
	}
	return 0
}

func (x *TimelineResponse) GetUnreadList() []uint64 {
	if x != nil {
		return x.UnreadList
	}
	return nil
}

// UserPageResponse 朋友圈用户页响应（镜像 golem.moments.UserPageResponse）
type UserPageResponse struct {
	state                 protoimpl.MessageState   `protogen:"open.v1"`
	BaseResponse          *base.BaseResponse       `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	FirstPageMd5          *string                  `protobuf:"bytes,2,opt,name=first_page_md5,json=firstPageMd5,proto3,oneof" json:"first_page_md5,omitempty"`
	ObjectCount           *uint32                  `protobuf:"varint,3,opt,name=object_count,json=objectCount,proto3,oneof" json:"object_count,omitempty"`
	ObjectList            []*message.MomentsObject `protobuf:"bytes,4,rep,name=object_list,json=objectList,proto3" json:"object_list,omitempty"`
	ObjectTotalCount      *uint32                  `protobuf:"varint,5,opt,name=object_total_count,json=objectTotalCount,proto3,oneof" json:"object_total_count,omitempty"`
	NewRequestTime        *uint32                  `protobuf:"varint,7,opt,name=new_request_time,json=newRequestTime,proto3,oneof" json:"new_request_time,omitempty"`
	ObjectCountForSameMd5 *uint32                  `protobuf:"varint,8,opt,name=object_count_for_same_md5,json=objectCountForSameMd5,proto3,oneof" json:"object_count_for_same_md5,omitempty"`
	ServerConfig          *ServerConfig            `protobuf:"bytes,9,opt,name=server_config,json=serverConfig,proto3,oneof" json:"server_config,omitempty"`
	LimitedId             *uint64                  `protobuf:"varint,10,opt,name=limited_id,json=limitedId,proto3,oneof" json:"limited_id,omitempty"`
	ContinueId            *uint64                  `protobuf:"varint,11,opt,name=continue_id,json=continueId,proto3,oneof" json:"continue_id,omitempty"`
	ReturnTips            *string                  `protobuf:"bytes,12,opt,name=return_tips,json=returnTips,proto3,oneof" json:"return_tips,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UserPageResponse) Reset() {
	*x = UserPageResponse{}
	mi := &file_api_moments_moments_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPageResponse) ProtoMessage() {}

func (x *UserPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_moments_moments_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPageResponse.ProtoReflect.Descriptor instead.
func (*UserPageResponse) Descriptor() ([]byte, []int) {
	return file_api_moments_moments_api_proto_rawDescGZIP(), []int{10}
}

func (x *UserPageResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *UserPageResponse) GetFirstPageMd5() string {
	if x != nil && x.FirstPageMd5 != nil {
		return *x.FirstPageMd5
	}
	return ""
}

func (x *UserPageResponse) GetObjectCount() uint32 {
	if x != nil && x.ObjectCount != nil {
		return *x.ObjectCount
	}
	return 0
}

func (x *UserPageResponse) GetObjectList() []*message.MomentsObject {
	if x != nil {
		return x.ObjectList
	}
	return nil
}

func (x *UserPageResponse) GetObjectTotalCount() uint32 {
	if x != nil && x.ObjectTotalCount != nil {
		return *x.ObjectTotalCount
	}
	return 0
}

func (x *UserPageResponse) GetNewRequestTime() uint32 {
	if x != nil && x.NewRequestTime != nil {
		return *x.NewRequestTime
	}
	return 0
}

func (x *UserPageResponse) GetObjectCountForSameMd5() uint32 {
	if x != nil && x.ObjectCountForSameMd5 != nil {
		return *x.ObjectCountForSameMd5
	}
	return 0
}

func (x *UserPageResponse) GetServerConfig() *ServerConfig {
	if x != nil {
		return x.ServerConfig
	}
	return nil
}

func (x *UserPageResponse) GetLimitedId() uint64 {
	if x != nil && x.LimitedId != nil {
		return *x.LimitedId
	}
	return 0
}

func (x *UserPageResponse) GetContinueId() uint64 {
	if x != nil && x.ContinueId != nil {
		return *x.ContinueId
	}
	return 0
}

func (x *UserPageResponse) GetReturnTips() string {
	if x != nil && x.ReturnTips != nil {
		return *x.ReturnTips
	}
	return ""
}

// DetailResponse 朋友圈详情响应（镜像 golem.moments.DetailResponse）
type DetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResponse  *base.BaseResponse     `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	Object        *message.MomentsObject `protobuf:"bytes,2,opt,name=object,proto3,oneof" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailResponse) Reset() {
	*x = DetailResponse{}
	mi := &file_api_moments_moments_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailResponse) ProtoMessage() {}

func (x *DetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_moments_moments_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailResponse.ProtoReflect.Descriptor instead.
func (*DetailResponse) Descriptor() ([]byte, []int) {
	return file_api_moments_moments_api_proto_rawDescGZIP(), []int{11}
}

func (x *DetailResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *DetailResponse) GetObject() *message.MomentsObject {
	if x != nil {
		return x.Object
	}
	return nil
}

// SyncResponse 朋友圈同步响应（镜像 golem.moments.SyncResponse）
type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResponse  *base.BaseResponse     `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	Commands      *base.Commands         `protobuf:"bytes,2,opt,name=commands,proto3,oneof" json:"commands,omitempty"`
	ContinueFlag  *uint32                `protobuf:"varint,3,opt,name=continue_flag,json=continueFlag,proto3,oneof" json:"continue_flag,omitempty"`
	Key           *base.Buffer           `protobuf:"bytes,4,opt,name=key,proto3,oneof" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_api_moments_moments_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_moments_moments_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_api_moments_moments_api_proto_rawDescGZIP(), []int{12}
}

func (x *SyncResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *SyncResponse) GetCommands() *base.Commands {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *SyncResponse) GetContinueFlag() uint32 {
	if x != nil && x.ContinueFlag != nil {
		return *x.ContinueFlag
	}
	return 0
}

func (x *SyncResponse) GetKey() *base.Buffer {
	if x != nil {
		return x.Key
	}
	return nil
}

// Advertise 广告信息（镜像 golem.moments.TimelineResponse.Advertise）
type TimelineResponse_Advertise struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Object        *ADObject               `protobuf:"bytes,1,opt,name=object,proto3,oneof" json:"object,omitempty"`
	Info          *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=info,proto3,oneof" json:"info,omitempty"`
	Pos           *uint32                 `protobuf:"varint,3,opt,name=pos,proto3,oneof" json:"pos,omitempty"`
	RemindInfo    *RemindFriendsInfo      `protobuf:"bytes,4,opt,name=remind_info,json=remindInfo,proto3,oneof" json:"remind_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineResponse_Advertise) Reset() {
	*x = TimelineResponse_Advertise{}
	mi := &file_api_moments_moments_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineResponse_Advertise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineResponse_Advertise) ProtoMessage() {}

func (x *TimelineResponse_Advertise) ProtoReflect() protoreflect.Message {
	mi := &file_api_moments_moments_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineResponse_Advertise.ProtoReflect.Descriptor instead.
func (*TimelineResponse_Advertise) Descriptor() ([]byte, []int) {
	return file_api_moments_moments_api_proto_rawDescGZIP(), []int{9, 0}
}

func (x *TimelineResponse_Advertise) GetObject() *ADObject {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *TimelineResponse_Advertise) GetInfo() *wrapperspb.StringValue {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *TimelineResponse_Advertise) GetPos() uint32 {
	if x != nil && x.Pos != nil {
		return *x.Pos
	}
	return 0
}

func (x *TimelineResponse_Advertise) GetRemindInfo() *RemindFriendsInfo {
	if x != nil {
		return x.RemindInfo
	}
	return nil
}

// Recommend 推荐信息（镜像 golem.moments.TimelineResponse.Recommend）
type TimelineResponse_Recommend struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Object        *TimelineResponse_Recommend_Object `protobuf:"bytes,1,opt,name=object,proto3,oneof" json:"object,omitempty"`
	Info          *wrapperspb.StringValue            `protobuf:"bytes,2,opt,name=info,proto3,oneof" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineResponse_Recommend) Reset() {
	*x = TimelineResponse_Recommend{}
	mi := &file_api_moments_moments_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineResponse_Recommend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineResponse_Recommend) ProtoMessage() {}

func (x *TimelineResponse_Recommend) ProtoReflect() protoreflect.Message {
	mi := &file_api_moments_moments_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineResponse_Recommend.ProtoReflect.Descriptor instead.
func (*TimelineResponse_Recommend) Descriptor() ([]byte, []int) {
	return file_api_moments_moments_api_proto_rawDescGZIP(), []int{9, 1}
}

func (x *TimelineResponse_Recommend) GetObject() *TimelineResponse_Recommend_Object {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *TimelineResponse_Recommend) GetInfo() *wrapperspb.StringValue {
	if x != nil {
		return x.Info
	}
	return nil
}

// Object 推荐对象（镜像 golem.moments.TimelineResponse.Recommend.Object）
type TimelineResponse_Recommend_Object struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	MomentsObject *message.MomentsObject  `protobuf:"bytes,1,opt,name=moments_object,json=momentsObject,proto3,oneof" json:"moments_object,omitempty"`
	RecommendXml  *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=recommend_xml,json=recommendXml,proto3,oneof" json:"recommend_xml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineResponse_Recommend_Object) Reset() {
	*x = TimelineResponse_Recommend_Object{}
	mi := &file_api_moments_moments_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineResponse_Recommend_Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineResponse_Recommend_Object) ProtoMessage() {}

func (x *TimelineResponse_Recommend_Object) ProtoReflect() protoreflect.Message {
	mi := &file_api_moments_moments_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineResponse_Recommend_Object.ProtoReflect.Descriptor instead.
func (*TimelineResponse_Recommend_Object) Descriptor() ([]byte, []int) {
	return file_api_moments_moments_api_proto_rawDescGZIP(), []int{9, 1, 0}
}

func (x *TimelineResponse_Recommend_Object) GetMomentsObject() *message.MomentsObject {
	if x != nil {
		return x.MomentsObject
	}
	return nil
}

func (x *TimelineResponse_Recommend_Object) GetRecommendXml() *wrapperspb.StringValue {
	if x != nil {
		return x.RecommendXml
	}
	return nil
}

var File_api_moments_moments_api_proto protoreflect.FileDescriptor

const file_api_moments_moments_api_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/moments/moments_api.proto\x12\vapi.moments\x1a\x13api/base/base.proto\x1a\x1capi/message/sync_types.proto\x1a\x1egoogle/protobuf/wrappers.proto\"Z\n" +
	"\vTwitterInfo\x12\x19\n" +
	"\x05token\x18\x01 \x01(\tH\x00R\x05token\x88\x01\x01\x12\x1b\n" +
	"\x06secret\x18\x02 \x01(\tH\x01R\x06secret\x88\x01\x01B\b\n" +
	"\x06_tokenB\t\n" +
	"\a_secret\"\x8d\x01\n" +
	"\tBufferUrl\x12\x15\n" +
	"\x03url\x18\x01 \x01(\tH\x00R\x03url\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\x02 \x01(\rH\x01R\x04type\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\x03 \x01(\rH\x02R\x04size\x88\x01\x01\x12\x15\n" +
	"\x03md5\x18\x04 \x01(\tH\x03R\x03md5\x88\x01\x01B\x06\n" +
	"\x04_urlB\a\n" +
	"\x05_typeB\a\n" +
	"\x05_sizeB\x06\n" +
	"\x04_md5\"\xb5\x01\n" +
	"\fServerConfig\x121\n" +
	"\x12post_mention_limit\x18\x01 \x01(\x05H\x00R\x10postMentionLimit\x88\x01\x01\x12=\n" +
	"\x19copy_and_paste_word_limit\x18\x02 \x01(\x05H\x01R\x15copyAndPasteWordLimit\x88\x01\x01B\x15\n" +
	"\x13_post_mention_limitB\x1c\n" +
	"\x1a_copy_and_paste_word_limit\"\x83\x01\n" +
	"\bADObject\x122\n" +
	"\x06object\x18\x01 \x01(\v2\x1a.api.message.MomentsObjectR\x06object\x128\n" +
	"\x06ad_xml\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueH\x00R\x05adXml\x88\x01\x01B\t\n" +
	"\a_ad_xml\"\xa2\x03\n" +
	"\x11RemindFriendsInfo\x12(\n" +
	"\radchatroom_id\x18\x01 \x01(\x04H\x00R\fadchatroomId\x88\x01\x01\x126\n" +
	"\vsource_info\x18\x02 \x01(\v2\x10.api.base.BufferH\x01R\n" +
	"sourceInfo\x88\x01\x01\x122\n" +
	"\tself_info\x18\x03 \x01(\v2\x10.api.base.BufferH\x02R\bselfInfo\x88\x01\x01\x122\n" +
	"\tpaid_info\x18\x04 \x01(\v2\x10.api.base.BufferH\x03R\bpaidInfo\x88\x01\x01\x124\n" +
	"\n" +
	"extra_info\x18\x05 \x01(\v2\x10.api.base.BufferH\x04R\textraInfo\x88\x01\x01\x12,\n" +
	"\x0fadchatroom_id64\x18\x06 \x01(\x04H\x05R\x0eadchatroomId64\x88\x01\x01B\x10\n" +
	"\x0e_adchatroom_idB\x0e\n" +
	"\f_source_infoB\f\n" +
	"\n" +
	"_self_infoB\f\n" +
	"\n" +
	"_paid_infoB\r\n" +
	"\v_extra_infoB\x12\n" +
	"\x10_adchatroom_id64\"\xd6\x01\n" +
	"\fPostResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x127\n" +
	"\x06object\x18\x02 \x01(\v2\x1a.api.message.MomentsObjectH\x01R\x06object\x88\x01\x01\x12 \n" +
	"\tspam_tips\x18\x03 \x01(\tH\x02R\bspamTips\x88\x01\x01B\x10\n" +
	"\x0e_base_responseB\t\n" +
	"\a_objectB\f\n" +
	"\n" +
	"_spam_tips\"\x9e\x01\n" +
	"\x0fOperateResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x12\x19\n" +
	"\x05count\x18\x02 \x01(\rH\x01R\x05count\x88\x01\x01\x12\x12\n" +
	"\x04list\x18\x03 \x03(\x05R\x04listB\x10\n" +
	"\x0e_base_responseB\b\n" +
	"\x06_count\"\xa9\x01\n" +
	"\x0fCommentResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x127\n" +
	"\x06object\x18\x02 \x01(\v2\x1a.api.message.MomentsObjectH\x01R\x06object\x88\x01\x01B\x10\n" +
	"\x0e_base_responseB\t\n" +
	"\a_object\"\xe6\x03\n" +
	"\x0eUploadResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x02 \x01(\rH\x01R\x06offset\x88\x01\x01\x12\x17\n" +
	"\x04size\x18\x03 \x01(\rH\x02R\x04size\x88\x01\x01\x12 \n" +
	"\tclient_id\x18\x04 \x01(\tH\x03R\bclientId\x88\x01\x01\x12:\n" +
	"\n" +
	"buffer_url\x18\x05 \x01(\v2\x16.api.moments.BufferUrlH\x04R\tbufferUrl\x88\x01\x01\x12+\n" +
	"\x0fthumb_url_count\x18\x06 \x01(\rH\x05R\rthumbUrlCount\x88\x01\x01\x12<\n" +
	"\x0ethumb_url_list\x18\a \x03(\v2\x16.api.moments.BufferUrlR\fthumbUrlList\x12\x13\n" +
	"\x02id\x18\b \x01(\x04H\x06R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\t \x01(\rH\aR\x04type\x88\x01\x01B\x10\n" +
	"\x0e_base_responseB\t\n" +
	"\a_offsetB\a\n" +
	"\x05_sizeB\f\n" +
	"\n" +
	"_client_idB\r\n" +
	"\v_buffer_urlB\x12\n" +
	"\x10_thumb_url_countB\x05\n" +
	"\x03_idB\a\n" +
	"\x05_type\"\x96\x0e\n" +
	"\x10TimelineResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x12)\n" +
	"\x0efirst_page_md5\x18\x02 \x01(\tH\x01R\ffirstPageMd5\x88\x01\x01\x12&\n" +
	"\fobject_count\x18\x03 \x01(\rH\x02R\vobjectCount\x88\x01\x01\x12;\n" +
	"\vobject_list\x18\x04 \x03(\v2\x1a.api.message.MomentsObjectR\n" +
	"objectList\x12-\n" +
	"\x10new_request_time\x18\x05 \x01(\rH\x03R\x0enewRequestTime\x88\x01\x01\x12=\n" +
	"\x19object_count_for_same_md5\x18\x06 \x01(\rH\x04R\x15objectCountForSameMd5\x88\x01\x01\x12&\n" +
	"\fcontrol_flag\x18\a \x01(\rH\x05R\vcontrolFlag\x88\x01\x01\x12C\n" +
	"\rserver_config\x18\b \x01(\v2\x19.api.moments.ServerConfigH\x06R\fserverConfig\x88\x01\x01\x12,\n" +
	"\x0fadvertise_count\x18\t \x01(\rH\aR\x0eadvertiseCount\x88\x01\x01\x12N\n" +
	"\x0eadvertise_list\x18\n" +
	" \x03(\v2'.api.moments.TimelineResponse.AdvertiseR\radvertiseList\x12/\n" +
	"\asession\x18\v \x01(\v2\x10.api.base.BufferH\bR\asession\x88\x01\x01\x12,\n" +
	"\x0frecommend_count\x18\f \x01(\rH\tR\x0erecommendCount\x88\x01\x01\x12N\n" +
	"\x0erecommend_list\x18\r \x03(\v2'.api.moments.TimelineResponse.RecommendR\rrecommendList\x129\n" +
	"\x16delete_advertise_count\x18\x0e \x01(\rH\n" +
	"R\x14deleteAdvertiseCount\x88\x01\x01\x12P\n" +
	"\x15delete_advertise_list\x18\x0f \x03(\v2\x1c.google.protobuf.UInt64ValueR\x13deleteAdvertiseList\x12&\n" +
	"\funread_count\x18\x10 \x01(\rH\vR\vunreadCount\x88\x01\x01\x12\x1f\n" +
	"\vunread_list\x18\x11 \x03(\x04R\n" +
	"unreadList\x1a\xff\x01\n" +
	"\tAdvertise\x122\n" +
	"\x06object\x18\x01 \x01(\v2\x15.api.moments.ADObjectH\x00R\x06object\x88\x01\x01\x125\n" +
	"\x04info\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueH\x01R\x04info\x88\x01\x01\x12\x15\n" +
	"\x03pos\x18\x03 \x01(\rH\x02R\x03pos\x88\x01\x01\x12D\n" +
	"\vremind_info\x18\x04 \x01(\v2\x1e.api.moments.RemindFriendsInfoH\x03R\n" +
	"remindInfo\x88\x01\x01B\t\n" +
	"\a_objectB\a\n" +
	"\x05_infoB\x06\n" +
	"\x04_posB\x0e\n" +
	"\f_remind_info\x1a\xe3\x02\n" +
	"\tRecommend\x12K\n" +
	"\x06object\x18\x01 \x01(\v2..api.moments.TimelineResponse.Recommend.ObjectH\x00R\x06object\x88\x01\x01\x125\n" +
	"\x04info\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueH\x01R\x04info\x88\x01\x01\x1a\xbd\x01\n" +
	"\x06Object\x12F\n" +
	"\x0emoments_object\x18\x01 \x01(\v2\x1a.api.message.MomentsObjectH\x00R\rmomentsObject\x88\x01\x01\x12F\n" +
	"\rrecommend_xml\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueH\x01R\frecommendXml\x88\x01\x01B\x11\n" +
	"\x0f_moments_objectB\x10\n" +
	"\x0e_recommend_xmlB\t\n" +
	"\a_objectB\a\n" +
	"\x05_infoB\x10\n" +
	"\x0e_base_responseB\x11\n" +
	"\x0f_first_page_md5B\x0f\n" +
	"\r_object_countB\x13\n" +
	"\x11_new_request_timeB\x1c\n" +
	"\x1a_object_count_for_same_md5B\x0f\n" +
	"\r_control_flagB\x10\n" +
	"\x0e_server_configB\x12\n" +
	"\x10_advertise_countB\n" +
	"\n" +
	"\b_sessionB\x12\n" +
	"\x10_recommend_countB\x19\n" +
	"\x17_delete_advertise_countB\x0f\n" +
	"\r_unread_count\"\xfb\x05\n" +
	"\x10UserPageResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x12)\n" +
	"\x0efirst_page_md5\x18\x02 \x01(\tH\x01R\ffirstPageMd5\x88\x01\x01\x12&\n" +
	"\fobject_count\x18\x03 \x01(\rH\x02R\vobjectCount\x88\x01\x01\x12;\n" +
	"\vobject_list\x18\x04 \x03(\v2\x1a.api.message.MomentsObjectR\n" +
	"objectList\x121\n" +
	"\x12object_total_count\x18\x05 \x01(\rH\x03R\x10objectTotalCount\x88\x01\x01\x12-\n" +
	"\x10new_request_time\x18\a \x01(\rH\x04R\x0enewRequestTime\x88\x01\x01\x12=\n" +
	"\x19object_count_for_same_md5\x18\b \x01(\rH\x05R\x15objectCountForSameMd5\x88\x01\x01\x12C\n" +
	"\rserver_config\x18\t \x01(\v2\x19.api.moments.ServerConfigH\x06R\fserverConfig\x88\x01\x01\x12\"\n" +
	"\n" +
	"limited_id\x18\n" +
	" \x01(\x04H\aR\tlimitedId\x88\x01\x01\x12$\n" +
	"\vcontinue_id\x18\v \x01(\x04H\bR\n" +
	"continueId\x88\x01\x01\x12$\n" +
	"\vreturn_tips\x18\f \x01(\tH\tR\n" +
	"returnTips\x88\x01\x01B\x10\n" +
	"\x0e_base_responseB\x11\n" +
	"\x0f_first_page_md5B\x0f\n" +
	"\r_object_countB\x15\n" +
	"\x13_object_total_countB\x13\n" +
	"\x11_new_request_timeB\x1c\n" +
	"\x1a_object_count_for_same_md5B\x10\n" +
	"\x0e_server_configB\r\n" +
	"\v_limited_idB\x0e\n" +
	"\f_continue_idB\x0e\n" +
	"\f_return_tips\"\xa8\x01\n" +
	"\x0eDetailResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x127\n" +
	"\x06object\x18\x02 \x01(\v2\x1a.api.message.MomentsObjectH\x01R\x06object\x88\x01\x01B\x10\n" +
	"\x0e_base_responseB\t\n" +
	"\a_object\"\x91\x02\n" +
	"\fSyncResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x123\n" +
	"\bcommands\x18\x02 \x01(\v2\x12.api.base.CommandsH\x01R\bcommands\x88\x01\x01\x12(\n" +
	"\rcontinue_flag\x18\x03 \x01(\rH\x02R\fcontinueFlag\x88\x01\x01\x12'\n" +
	"\x03key\x18\x04 \x01(\v2\x10.api.base.BufferH\x03R\x03key\x88\x01\x01B\x10\n" +
	"\x0e_base_responseB\v\n" +
	"\t_commandsB\x10\n" +
	"\x0e_continue_flagB\x06\n" +
	"\x04_keyB7Z5github.com/sbgayhub/golem/host/api/moments;momentsapib\x06proto3"

var (
	file_api_moments_moments_api_proto_rawDescOnce sync.Once
	file_api_moments_moments_api_proto_rawDescData []byte
)

func file_api_moments_moments_api_proto_rawDescGZIP() []byte {
	file_api_moments_moments_api_proto_rawDescOnce.Do(func() {
		file_api_moments_moments_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_moments_moments_api_proto_rawDesc), len(file_api_moments_moments_api_proto_rawDesc)))
	})
	return file_api_moments_moments_api_proto_rawDescData
}

var file_api_moments_moments_api_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_moments_moments_api_proto_goTypes = []any{
	(*TwitterInfo)(nil),                       // 0: api.moments.TwitterInfo
	(*BufferUrl)(nil),                         // 1: api.moments.BufferUrl
	(*ServerConfig)(nil),                      // 2: api.moments.ServerConfig
	(*ADObject)(nil),                          // 3: api.moments.ADObject
	(*RemindFriendsInfo)(nil),                 // 4: api.moments.RemindFriendsInfo
	(*PostResponse)(nil),                      // 5: api.moments.PostResponse
	(*OperateResponse)(nil),                   // 6: api.moments.OperateResponse
	(*CommentResponse)(nil),                   // 7: api.moments.CommentResponse
	(*UploadResponse)(nil),                    // 8: api.moments.UploadResponse
	(*TimelineResponse)(nil),                  // 9: api.moments.TimelineResponse
	(*UserPageResponse)(nil),                  // 10: api.moments.UserPageResponse
	(*DetailResponse)(nil),                    // 11: api.moments.DetailResponse
	(*SyncResponse)(nil),                      // 12: api.moments.SyncResponse
	(*TimelineResponse_Advertise)(nil),        // 13: api.moments.TimelineResponse.Advertise
	(*TimelineResponse_Recommend)(nil),        // 14: api.moments.TimelineResponse.Recommend
	(*TimelineResponse_Recommend_Object)(nil), // 15: api.moments.TimelineResponse.Recommend.Object
	(*message.MomentsObject)(nil),             // 16: api.message.MomentsObject
	(*wrapperspb.StringValue)(nil),            // 17: google.protobuf.StringValue
	(*base.Buffer)(nil),                       // 18: api.base.Buffer
	(*base.BaseResponse)(nil),                 // 19: api.base.BaseResponse
	(*wrapperspb.UInt64Value)(nil),            // 20: google.protobuf.UInt64Value
	(*base.Commands)(nil),                     // 21: api.base.Commands
}
var file_api_moments_moments_api_proto_depIdxs = []int32{
	16, // 0: api.moments.ADObject.object:type_name -> api.message.MomentsObject
	17, // 1: api.moments.ADObject.ad_xml:type_name -> google.protobuf.StringValue
	18, // 2: api.moments.RemindFriendsInfo.source_info:type_name -> api.base.Buffer
	18, // 3: api.moments.RemindFriendsInfo.self_info:type_name -> api.base.Buffer
	18, // 4: api.moments.RemindFriendsInfo.paid_info:type_name -> api.base.Buffer
	18, // 5: api.moments.RemindFriendsInfo.extra_info:type_name -> api.base.Buffer
	19, // 6: api.moments.PostResponse.base_response:type_name -> api.base.BaseResponse
	16, // 7: api.moments.PostResponse.object:type_name -> api.message.MomentsObject
	19, // 8: api.moments.OperateResponse.base_response:type_name -> api.base.BaseResponse
	19, // 9: api.moments.CommentResponse.base_response:type_name -> api.base.BaseResponse
	16, // 10: api.moments.CommentResponse.object:type_name -> api.message.MomentsObject
	19, // 11: api.moments.UploadResponse.base_response:type_name -> api.base.BaseResponse
	1,  // 12: api.moments.UploadResponse.buffer_url:type_name -> api.moments.BufferUrl
	1,  // 13: api.moments.UploadResponse.thumb_url_list:type_name -> api.moments.BufferUrl
	19, // 14: api.moments.TimelineResponse.base_response:type_name -> api.base.BaseResponse
	16, // 15: api.moments.TimelineResponse.object_list:type_name -> api.message.MomentsObject
	2,  // 16: api.moments.TimelineResponse.server_config:type_name -> api.moments.ServerConfig
	13, // 17: api.moments.TimelineResponse.advertise_list:type_name -> api.moments.TimelineResponse.Advertise
	18, // 18: api.moments.TimelineResponse.session:type_name -> api.base.Buffer
	14, // 19: api.moments.TimelineResponse.recommend_list:type_name -> api.moments.TimelineResponse.Recommend
	20, // 20: api.moments.TimelineResponse.delete_advertise_list:type_name -> google.protobuf.UInt64Value
	19, // 21: api.moments.UserPageResponse.base_response:type_name -> api.base.BaseResponse
	16, // 22: api.moments.UserPageResponse.object_list:type_name -> api.message.MomentsObject
	2,  // 23: api.moments.UserPageResponse.server_config:type_name -> api.moments.ServerConfig
	19, // 24: api.moments.DetailResponse.base_response:type_name -> api.base.BaseResponse
	16, // 25: api.moments.DetailResponse.object:type_name -> api.message.MomentsObject
	19, // 26: api.moments.SyncResponse.base_response:type_name -> api.base.BaseResponse
	21, // 27: api.moments.SyncResponse.commands:type_name -> api.base.Commands
	18, // 28: api.moments.SyncResponse.key:type_name -> api.base.Buffer
	3,  // 29: api.moments.TimelineResponse.Advertise.object:type_name -> api.moments.ADObject
	17, // 30: api.moments.TimelineResponse.Advertise.info:type_name -> google.protobuf.StringValue
	4,  // 31: api.moments.TimelineResponse.Advertise.remind_info:type_name -> api.moments.RemindFriendsInfo
	15, // 32: api.moments.TimelineResponse.Recommend.object:type_name -> api.moments.TimelineResponse.Recommend.Object
	17, // 33: api.moments.TimelineResponse.Recommend.info:type_name -> google.protobuf.StringValue
	16, // 34: api.moments.TimelineResponse.Recommend.Object.moments_object:type_name -> api.message.MomentsObject
	17, // 35: api.moments.TimelineResponse.Recommend.Object.recommend_xml:type_name -> google.protobuf.StringValue
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_api_moments_moments_api_proto_init() }
func file_api_moments_moments_api_proto_init() {
	if File_api_moments_moments_api_proto != nil {
		return
	}
	file_api_moments_moments_api_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_moments_moments_api_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_moments_moments_api_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_moments_moments_api_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_moments_moments_api_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_moments_moments_api_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_moments_moments_api_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_moments_moments_api_proto_msgTypes[7].OneofWrappers = []any{}
	file_api_moments_moments_api_proto_msgTypes[8].OneofWrappers = []any{}
	file_api_moments_moments_api_proto_msgTypes[9].OneofWrappers = []any{}
	file_api_moments_moments_api_proto_msgTypes[10].OneofWrappers = []any{}
	file_api_moments_moments_api_proto_msgTypes[11].OneofWrappers = []any{}
	file_api_moments_moments_api_proto_msgTypes[12].OneofWrappers = []any{}
	file_api_moments_moments_api_proto_msgTypes[13].OneofWrappers = []any{}
	file_api_moments_moments_api_proto_msgTypes[14].OneofWrappers = []any{}
	file_api_moments_moments_api_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_moments_moments_api_proto_rawDesc), len(file_api_moments_moments_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_moments_moments_api_proto_goTypes,
		DependencyIndexes: file_api_moments_moments_api_proto_depIdxs,
		MessageInfos:      file_api_moments_moments_api_proto_msgTypes,
	}.Build()
	File_api_moments_moments_api_proto = out.File
	file_api_moments_moments_api_proto_goTypes = nil
	file_api_moments_moments_api_proto_depIdxs = nil
}
