// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/official/official_api.proto

package officialapi

import (
	base "github.com/sbgayhub/golem/host/api/base"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetA8KeyResponse 获取公众号 A8Key 响应（镜像 golem.official.GetA8KeyResponse）
type GetA8KeyResponse struct {
	state             protoimpl.MessageState                  `protogen:"open.v1"`
	BaseResponse      *base.BaseResponse                      `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	FullUrl           *string                                 `protobuf:"bytes,2,opt,name=full_url,json=fullUrl,proto3,oneof" json:"full_url,omitempty"`
	A8Key             *string                                 `protobuf:"bytes,3,opt,name=a8_key,json=a8Key,proto3,oneof" json:"a8_key,omitempty"`
	ActionCode        *string                                 `protobuf:"bytes,4,opt,name=action_code,json=actionCode,proto3,oneof" json:"action_code,omitempty"`
	Title             *string                                 `protobuf:"bytes,5,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Content           *string                                 `protobuf:"bytes,6,opt,name=content,proto3,oneof" json:"content,omitempty"`
	JsapiPermission   *GetA8KeyResponse_JSAPIPermissionBitSet `protobuf:"bytes,7,opt,name=jsapi_permission,json=jsapiPermission,proto3,oneof" json:"jsapi_permission,omitempty"`
	GeneralControl    *wrapperspb.UInt32Value                 `protobuf:"bytes,8,opt,name=general_control,json=generalControl,proto3,oneof" json:"general_control,omitempty"`
	UserName          *string                                 `protobuf:"bytes,9,opt,name=user_name,json=userName,proto3,oneof" json:"user_name,omitempty"`
	ShareUrl          *string                                 `protobuf:"bytes,15,opt,name=share_url,json=shareUrl,proto3,oneof" json:"share_url,omitempty"`
	ScopeCount        *uint32                                 `protobuf:"varint,16,opt,name=scope_count,json=scopeCount,proto3,oneof" json:"scope_count,omitempty"`
	ScopeList         []*GetA8KeyResponse_BizScopeInfo        `protobuf:"bytes,17,rep,name=scope_list,json=scopeList,proto3" json:"scope_list,omitempty"`
	AntispamTicket    *string                                 `protobuf:"bytes,18,opt,name=antispam_ticket,json=antispamTicket,proto3,oneof" json:"antispam_ticket,omitempty"`
	Ssid              *string                                 `protobuf:"bytes,20,opt,name=ssid,proto3,oneof" json:"ssid,omitempty"`
	Mid               *string                                 `protobuf:"bytes,21,opt,name=mid,proto3,oneof" json:"mid,omitempty"`
	DeepLink          *wrapperspb.UInt64Value                 `protobuf:"bytes,22,opt,name=deep_link,json=deepLink,proto3,oneof" json:"deep_link,omitempty"`
	JsapiControlBytes *base.Buffer                            `protobuf:"bytes,23,opt,name=jsapi_control_bytes,json=jsapiControlBytes,proto3,oneof" json:"jsapi_control_bytes,omitempty"`
	HttpHeaderCount   *uint32                                 `protobuf:"varint,24,opt,name=http_header_count,json=httpHeaderCount,proto3,oneof" json:"http_header_count,omitempty"`
	HttpHeaderList    []*GetA8KeyResponse_HttpHeader          `protobuf:"bytes,25,rep,name=http_header_list,json=httpHeaderList,proto3" json:"http_header_list,omitempty"`
	Wording           *string                                 `protobuf:"bytes,26,opt,name=wording,proto3,oneof" json:"wording,omitempty"`
	Avatar            *string                                 `protobuf:"bytes,27,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	Cookie            *base.Buffer                            `protobuf:"bytes,28,opt,name=cookie,proto3,oneof" json:"cookie,omitempty"`
	MenuWording       *string                                 `protobuf:"bytes,29,opt,name=menu_wording,json=menuWording,proto3,oneof" json:"menu_wording,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetA8KeyResponse) Reset() {
	*x = GetA8KeyResponse{}
	mi := &file_api_official_official_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetA8KeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetA8KeyResponse) ProtoMessage() {}

func (x *GetA8KeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_official_official_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetA8KeyResponse.ProtoReflect.Descriptor instead.
func (*GetA8KeyResponse) Descriptor() ([]byte, []int) {
	return file_api_official_official_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetA8KeyResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *GetA8KeyResponse) GetFullUrl() string {
	if x != nil && x.FullUrl != nil {
		return *x.FullUrl
	}
	return ""
}

func (x *GetA8KeyResponse) GetA8Key() string {
	if x != nil && x.A8Key != nil {
		return *x.A8Key
	}
	return ""
}

func (x *GetA8KeyResponse) GetActionCode() string {
	if x != nil && x.ActionCode != nil {
		return *x.ActionCode
	}
	return ""
}

func (x *GetA8KeyResponse) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *GetA8KeyResponse) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *GetA8KeyResponse) GetJsapiPermission() *GetA8KeyResponse_JSAPIPermissionBitSet {
	if x != nil {
		return x.JsapiPermission
	}
	return nil
}

func (x *GetA8KeyResponse) GetGeneralControl() *wrapperspb.UInt32Value {
	if x != nil {
		return x.GeneralControl
	}
	return nil
}

func (x *GetA8KeyResponse) GetUserName() string {
	if x != nil && x.UserName != nil {
		return *x.UserName
	}
	return ""
}

func (x *GetA8KeyResponse) GetShareUrl() string {
	if x != nil && x.ShareUrl != nil {
		return *x.ShareUrl
	}
	return ""
}

func (x *GetA8KeyResponse) GetScopeCount() uint32 {
	if x != nil && x.ScopeCount != nil {
		return *x.ScopeCount
	}
	return 0
}

func (x *GetA8KeyResponse) GetScopeList() []*GetA8KeyResponse_BizScopeInfo {
	if x != nil {
		return x.ScopeList
	}
	return nil
}

func (x *GetA8KeyResponse) GetAntispamTicket() string {
	if x != nil && x.AntispamTicket != nil {
		return *x.AntispamTicket
	}
	return ""
}

func (x *GetA8KeyResponse) GetSsid() string {
	if x != nil && x.Ssid != nil {
		return *x.Ssid
	}
	return ""
}

func (x *GetA8KeyResponse) GetMid() string {
	if x != nil && x.Mid != nil {
		return *x.Mid
	}
	return ""
}

func (x *GetA8KeyResponse) GetDeepLink() *wrapperspb.UInt64Value {
	if x != nil {
		return x.DeepLink
	}
	return nil
}

func (x *GetA8KeyResponse) GetJsapiControlBytes() *base.Buffer {
	if x != nil {
		return x.JsapiControlBytes
	}
	return nil
}

func (x *GetA8KeyResponse) GetHttpHeaderCount() uint32 {
	if x != nil && x.HttpHeaderCount != nil {
		return *x.HttpHeaderCount
	}
	return 0
}

func (x *GetA8KeyResponse) GetHttpHeaderList() []*GetA8KeyResponse_HttpHeader {
	if x != nil {
		return x.HttpHeaderList
	}
	return nil
}

func (x *GetA8KeyResponse) GetWording() string {
	if x != nil && x.Wording != nil {
		return *x.Wording
	}
	return ""
}

func (x *GetA8KeyResponse) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *GetA8KeyResponse) GetCookie() *base.Buffer {
	if x != nil {
		return x.Cookie
	}
	return nil
}

func (x *GetA8KeyResponse) GetMenuWording() string {
	if x != nil && x.MenuWording != nil {
		return *x.MenuWording
	}
	return ""
}

// JSAPIPreVerifyResponse JSAPI 预验证响应（镜像 golem.official.JSAPIPreVerifyResponse）
type JSAPIPreVerifyResponse struct {
	state          protoimpl.MessageState              `protogen:"open.v1"`
	BaseResponse   *base.BaseResponse                  `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	JsapiResult    *JSAPIPreVerifyResponse_JSAPIResult `protobuf:"bytes,2,opt,name=jsapi_result,json=jsapiResult,proto3,oneof" json:"jsapi_result,omitempty"`
	VerifyInfoList []string                            `protobuf:"bytes,3,rep,name=verify_info_list,json=verifyInfoList,proto3" json:"verify_info_list,omitempty"`
	DomainPathList []string                            `protobuf:"bytes,4,rep,name=domain_path_list,json=domainPathList,proto3" json:"domain_path_list,omitempty"`
	AppAvatarUrl   *string                             `protobuf:"bytes,5,opt,name=app_avatar_url,json=appAvatarUrl,proto3,oneof" json:"app_avatar_url,omitempty"`
	AppNickname    *string                             `protobuf:"bytes,6,opt,name=app_nickname,json=appNickname,proto3,oneof" json:"app_nickname,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JSAPIPreVerifyResponse) Reset() {
	*x = JSAPIPreVerifyResponse{}
	mi := &file_api_official_official_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSAPIPreVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSAPIPreVerifyResponse) ProtoMessage() {}

func (x *JSAPIPreVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_official_official_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSAPIPreVerifyResponse.ProtoReflect.Descriptor instead.
func (*JSAPIPreVerifyResponse) Descriptor() ([]byte, []int) {
	return file_api_official_official_api_proto_rawDescGZIP(), []int{1}
}

func (x *JSAPIPreVerifyResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *JSAPIPreVerifyResponse) GetJsapiResult() *JSAPIPreVerifyResponse_JSAPIResult {
	if x != nil {
		return x.JsapiResult
	}
	return nil
}

func (x *JSAPIPreVerifyResponse) GetVerifyInfoList() []string {
	if x != nil {
		return x.VerifyInfoList
	}
	return nil
}

func (x *JSAPIPreVerifyResponse) GetDomainPathList() []string {
	if x != nil {
		return x.DomainPathList
	}
	return nil
}

func (x *JSAPIPreVerifyResponse) GetAppAvatarUrl() string {
	if x != nil && x.AppAvatarUrl != nil {
		return *x.AppAvatarUrl
	}
	return ""
}

func (x *JSAPIPreVerifyResponse) GetAppNickname() string {
	if x != nil && x.AppNickname != nil {
		return *x.AppNickname
	}
	return ""
}

// OauthAuthorizeResponse OAuth 授权响应（镜像 golem.official.OauthAuthorizeResponse）
type OauthAuthorizeResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	BaseResponse            *base.BaseResponse     `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3,oneof" json:"base_response,omitempty"`
	ScopeList               [][]byte               `protobuf:"bytes,2,rep,name=scope_list,json=scopeList,proto3" json:"scope_list,omitempty"`
	AppName                 *string                `protobuf:"bytes,4,opt,name=app_name,json=appName,proto3,oneof" json:"app_name,omitempty"`
	AppIconUrl              *string                `protobuf:"bytes,5,opt,name=app_icon_url,json=appIconUrl,proto3,oneof" json:"app_icon_url,omitempty"`
	RedirectUrl             *string                `protobuf:"bytes,6,opt,name=redirect_url,json=redirectUrl,proto3,oneof" json:"redirect_url,omitempty"`
	IsRecentHasAuth         *bool                  `protobuf:"varint,9,opt,name=is_recent_has_auth,json=isRecentHasAuth,proto3,oneof" json:"is_recent_has_auth,omitempty"`
	IsSilentAuth            *bool                  `protobuf:"varint,10,opt,name=is_silent_auth,json=isSilentAuth,proto3,oneof" json:"is_silent_auth,omitempty"`
	IsCallServerWhenConfirm *bool                  `protobuf:"varint,11,opt,name=is_call_server_when_confirm,json=isCallServerWhenConfirm,proto3,oneof" json:"is_call_server_when_confirm,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *OauthAuthorizeResponse) Reset() {
	*x = OauthAuthorizeResponse{}
	mi := &file_api_official_official_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthAuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthAuthorizeResponse) ProtoMessage() {}

func (x *OauthAuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_official_official_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthAuthorizeResponse.ProtoReflect.Descriptor instead.
func (*OauthAuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_api_official_official_api_proto_rawDescGZIP(), []int{2}
}

func (x *OauthAuthorizeResponse) GetBaseResponse() *base.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *OauthAuthorizeResponse) GetScopeList() [][]byte {
	if x != nil {
		return x.ScopeList
	}
	return nil
}

func (x *OauthAuthorizeResponse) GetAppName() string {
	if x != nil && x.AppName != nil {
		return *x.AppName
	}
	return ""
}

func (x *OauthAuthorizeResponse) GetAppIconUrl() string {
	if x != nil && x.AppIconUrl != nil {
		return *x.AppIconUrl
	}
	return ""
}

func (x *OauthAuthorizeResponse) GetRedirectUrl() string {
	if x != nil && x.RedirectUrl != nil {
		return *x.RedirectUrl
	}
	return ""
}

func (x *OauthAuthorizeResponse) GetIsRecentHasAuth() bool {
	if x != nil && x.IsRecentHasAuth != nil {
		return *x.IsRecentHasAuth
	}
	return false
}

func (x *OauthAuthorizeResponse) GetIsSilentAuth() bool {
	if x != nil && x.IsSilentAuth != nil {
		return *x.IsSilentAuth
	}
	return false
}

func (x *OauthAuthorizeResponse) GetIsCallServerWhenConfirm() bool {
	if x != nil && x.IsCallServerWhenConfirm != nil {
		return *x.IsCallServerWhenConfirm
	}
	return false
}

// ArticleResult 公众号文章操作结果（golem 普通 Go struct）
type ArticleResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseBody  string                 `protobuf:"bytes,1,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	Cookies       string                 `protobuf:"bytes,2,opt,name=cookies,proto3" json:"cookies,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleResult) Reset() {
	*x = ArticleResult{}
	mi := &file_api_official_official_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleResult) ProtoMessage() {}

func (x *ArticleResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_official_official_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleResult.ProtoReflect.Descriptor instead.
func (*ArticleResult) Descriptor() ([]byte, []int) {
	return file_api_official_official_api_proto_rawDescGZIP(), []int{3}
}

func (x *ArticleResult) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *ArticleResult) GetCookies() string {
	if x != nil {
		return x.Cookies
	}
	return ""
}

func (x *ArticleResult) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

// JSAPIPermissionBitSet JSAPI 权限位集
type GetA8KeyResponse_JSAPIPermissionBitSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value1        *uint32                `protobuf:"varint,1,opt,name=value1,proto3,oneof" json:"value1,omitempty"`
	Value2        *uint32                `protobuf:"varint,2,opt,name=value2,proto3,oneof" json:"value2,omitempty"`
	Value3        *uint32                `protobuf:"varint,3,opt,name=value3,proto3,oneof" json:"value3,omitempty"`
	Value4        *uint32                `protobuf:"varint,4,opt,name=value4,proto3,oneof" json:"value4,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetA8KeyResponse_JSAPIPermissionBitSet) Reset() {
	*x = GetA8KeyResponse_JSAPIPermissionBitSet{}
	mi := &file_api_official_official_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetA8KeyResponse_JSAPIPermissionBitSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetA8KeyResponse_JSAPIPermissionBitSet) ProtoMessage() {}

func (x *GetA8KeyResponse_JSAPIPermissionBitSet) ProtoReflect() protoreflect.Message {
	mi := &file_api_official_official_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetA8KeyResponse_JSAPIPermissionBitSet.ProtoReflect.Descriptor instead.
func (*GetA8KeyResponse_JSAPIPermissionBitSet) Descriptor() ([]byte, []int) {
	return file_api_official_official_api_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetA8KeyResponse_JSAPIPermissionBitSet) GetValue1() uint32 {
	if x != nil && x.Value1 != nil {
		return *x.Value1
	}
	return 0
}

func (x *GetA8KeyResponse_JSAPIPermissionBitSet) GetValue2() uint32 {
	if x != nil && x.Value2 != nil {
		return *x.Value2
	}
	return 0
}

func (x *GetA8KeyResponse_JSAPIPermissionBitSet) GetValue3() uint32 {
	if x != nil && x.Value3 != nil {
		return *x.Value3
	}
	return 0
}

func (x *GetA8KeyResponse_JSAPIPermissionBitSet) GetValue4() uint32 {
	if x != nil && x.Value4 != nil {
		return *x.Value4
	}
	return 0
}

// BizScopeInfo 业务授权范围信息
type GetA8KeyResponse_BizScopeInfo struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	Scope            *string                   `protobuf:"bytes,1,opt,name=scope,proto3,oneof" json:"scope,omitempty"`
	ScopeStatus      *uint32                   `protobuf:"varint,2,opt,name=scope_status,json=scopeStatus,proto3,oneof" json:"scope_status,omitempty"`
	ScopeDescription *string                   `protobuf:"bytes,3,opt,name=scope_description,json=scopeDescription,proto3,oneof" json:"scope_description,omitempty"`
	ApiCount         *uint32                   `protobuf:"varint,4,opt,name=api_count,json=apiCount,proto3,oneof" json:"api_count,omitempty"`
	ApiList          []*wrapperspb.StringValue `protobuf:"bytes,5,rep,name=api_list,json=apiList,proto3" json:"api_list,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetA8KeyResponse_BizScopeInfo) Reset() {
	*x = GetA8KeyResponse_BizScopeInfo{}
	mi := &file_api_official_official_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetA8KeyResponse_BizScopeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetA8KeyResponse_BizScopeInfo) ProtoMessage() {}

func (x *GetA8KeyResponse_BizScopeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_official_official_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetA8KeyResponse_BizScopeInfo.ProtoReflect.Descriptor instead.
func (*GetA8KeyResponse_BizScopeInfo) Descriptor() ([]byte, []int) {
	return file_api_official_official_api_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GetA8KeyResponse_BizScopeInfo) GetScope() string {
	if x != nil && x.Scope != nil {
		return *x.Scope
	}
	return ""
}

func (x *GetA8KeyResponse_BizScopeInfo) GetScopeStatus() uint32 {
	if x != nil && x.ScopeStatus != nil {
		return *x.ScopeStatus
	}
	return 0
}

func (x *GetA8KeyResponse_BizScopeInfo) GetScopeDescription() string {
	if x != nil && x.ScopeDescription != nil {
		return *x.ScopeDescription
	}
	return ""
}

func (x *GetA8KeyResponse_BizScopeInfo) GetApiCount() uint32 {
	if x != nil && x.ApiCount != nil {
		return *x.ApiCount
	}
	return 0
}

func (x *GetA8KeyResponse_BizScopeInfo) GetApiList() []*wrapperspb.StringValue {
	if x != nil {
		return x.ApiList
	}
	return nil
}

// HttpHeader HTTP 头
type GetA8KeyResponse_HttpHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Value         *string                `protobuf:"bytes,2,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetA8KeyResponse_HttpHeader) Reset() {
	*x = GetA8KeyResponse_HttpHeader{}
	mi := &file_api_official_official_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetA8KeyResponse_HttpHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetA8KeyResponse_HttpHeader) ProtoMessage() {}

func (x *GetA8KeyResponse_HttpHeader) ProtoReflect() protoreflect.Message {
	mi := &file_api_official_official_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetA8KeyResponse_HttpHeader.ProtoReflect.Descriptor instead.
func (*GetA8KeyResponse_HttpHeader) Descriptor() ([]byte, []int) {
	return file_api_official_official_api_proto_rawDescGZIP(), []int{0, 2}
}

func (x *GetA8KeyResponse_HttpHeader) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *GetA8KeyResponse_HttpHeader) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

// JSAPIResult JSAPI 基础响应
type JSAPIPreVerifyResponse_JSAPIResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *int32                 `protobuf:"varint,1,opt,name=code,proto3,oneof" json:"code,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Json          *string                `protobuf:"bytes,3,opt,name=json,proto3,oneof" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSAPIPreVerifyResponse_JSAPIResult) Reset() {
	*x = JSAPIPreVerifyResponse_JSAPIResult{}
	mi := &file_api_official_official_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSAPIPreVerifyResponse_JSAPIResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSAPIPreVerifyResponse_JSAPIResult) ProtoMessage() {}

func (x *JSAPIPreVerifyResponse_JSAPIResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_official_official_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSAPIPreVerifyResponse_JSAPIResult.ProtoReflect.Descriptor instead.
func (*JSAPIPreVerifyResponse_JSAPIResult) Descriptor() ([]byte, []int) {
	return file_api_official_official_api_proto_rawDescGZIP(), []int{1, 0}
}

func (x *JSAPIPreVerifyResponse_JSAPIResult) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *JSAPIPreVerifyResponse_JSAPIResult) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *JSAPIPreVerifyResponse_JSAPIResult) GetJson() string {
	if x != nil && x.Json != nil {
		return *x.Json
	}
	return ""
}

var File_api_official_official_api_proto protoreflect.FileDescriptor

const file_api_official_official_api_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/official/official_api.proto\x12\fapi.official\x1a\x13api/base/base.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xbb\x0f\n" +
	"\x10GetA8KeyResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x12\x1e\n" +
	"\bfull_url\x18\x02 \x01(\tH\x01R\afullUrl\x88\x01\x01\x12\x1a\n" +
	"\x06a8_key\x18\x03 \x01(\tH\x02R\x05a8Key\x88\x01\x01\x12$\n" +
	"\vaction_code\x18\x04 \x01(\tH\x03R\n" +
	"actionCode\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\x05 \x01(\tH\x04R\x05title\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\x06 \x01(\tH\x05R\acontent\x88\x01\x01\x12d\n" +
	"\x10jsapi_permission\x18\a \x01(\v24.api.official.GetA8KeyResponse.JSAPIPermissionBitSetH\x06R\x0fjsapiPermission\x88\x01\x01\x12J\n" +
	"\x0fgeneral_control\x18\b \x01(\v2\x1c.google.protobuf.UInt32ValueH\aR\x0egeneralControl\x88\x01\x01\x12 \n" +
	"\tuser_name\x18\t \x01(\tH\bR\buserName\x88\x01\x01\x12 \n" +
	"\tshare_url\x18\x0f \x01(\tH\tR\bshareUrl\x88\x01\x01\x12$\n" +
	"\vscope_count\x18\x10 \x01(\rH\n" +
	"R\n" +
	"scopeCount\x88\x01\x01\x12J\n" +
	"\n" +
	"scope_list\x18\x11 \x03(\v2+.api.official.GetA8KeyResponse.BizScopeInfoR\tscopeList\x12,\n" +
	"\x0fantispam_ticket\x18\x12 \x01(\tH\vR\x0eantispamTicket\x88\x01\x01\x12\x17\n" +
	"\x04ssid\x18\x14 \x01(\tH\fR\x04ssid\x88\x01\x01\x12\x15\n" +
	"\x03mid\x18\x15 \x01(\tH\rR\x03mid\x88\x01\x01\x12>\n" +
	"\tdeep_link\x18\x16 \x01(\v2\x1c.google.protobuf.UInt64ValueH\x0eR\bdeepLink\x88\x01\x01\x12E\n" +
	"\x13jsapi_control_bytes\x18\x17 \x01(\v2\x10.api.base.BufferH\x0fR\x11jsapiControlBytes\x88\x01\x01\x12/\n" +
	"\x11http_header_count\x18\x18 \x01(\rH\x10R\x0fhttpHeaderCount\x88\x01\x01\x12S\n" +
	"\x10http_header_list\x18\x19 \x03(\v2).api.official.GetA8KeyResponse.HttpHeaderR\x0ehttpHeaderList\x12\x1d\n" +
	"\awording\x18\x1a \x01(\tH\x11R\awording\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\x1b \x01(\tH\x12R\x06avatar\x88\x01\x01\x12-\n" +
	"\x06cookie\x18\x1c \x01(\v2\x10.api.base.BufferH\x13R\x06cookie\x88\x01\x01\x12&\n" +
	"\fmenu_wording\x18\x1d \x01(\tH\x14R\vmenuWording\x88\x01\x01\x1a\xb7\x01\n" +
	"\x15JSAPIPermissionBitSet\x12\x1b\n" +
	"\x06value1\x18\x01 \x01(\rH\x00R\x06value1\x88\x01\x01\x12\x1b\n" +
	"\x06value2\x18\x02 \x01(\rH\x01R\x06value2\x88\x01\x01\x12\x1b\n" +
	"\x06value3\x18\x03 \x01(\rH\x02R\x06value3\x88\x01\x01\x12\x1b\n" +
	"\x06value4\x18\x04 \x01(\rH\x03R\x06value4\x88\x01\x01B\t\n" +
	"\a_value1B\t\n" +
	"\a_value2B\t\n" +
	"\a_value3B\t\n" +
	"\a_value4\x1a\x9d\x02\n" +
	"\fBizScopeInfo\x12\x19\n" +
	"\x05scope\x18\x01 \x01(\tH\x00R\x05scope\x88\x01\x01\x12&\n" +
	"\fscope_status\x18\x02 \x01(\rH\x01R\vscopeStatus\x88\x01\x01\x120\n" +
	"\x11scope_description\x18\x03 \x01(\tH\x02R\x10scopeDescription\x88\x01\x01\x12 \n" +
	"\tapi_count\x18\x04 \x01(\rH\x03R\bapiCount\x88\x01\x01\x127\n" +
	"\bapi_list\x18\x05 \x03(\v2\x1c.google.protobuf.StringValueR\aapiListB\b\n" +
	"\x06_scopeB\x0f\n" +
	"\r_scope_statusB\x14\n" +
	"\x12_scope_descriptionB\f\n" +
	"\n" +
	"_api_count\x1aP\n" +
	"\n" +
	"HttpHeader\x12\x15\n" +
	"\x03key\x18\x01 \x01(\tH\x00R\x03key\x88\x01\x01\x12\x19\n" +
	"\x05value\x18\x02 \x01(\tH\x01R\x05value\x88\x01\x01B\x06\n" +
	"\x04_keyB\b\n" +
	"\x06_valueB\x10\n" +
	"\x0e_base_responseB\v\n" +
	"\t_full_urlB\t\n" +
	"\a_a8_keyB\x0e\n" +
	"\f_action_codeB\b\n" +
	"\x06_titleB\n" +
	"\n" +
	"\b_contentB\x13\n" +
	"\x11_jsapi_permissionB\x12\n" +
	"\x10_general_controlB\f\n" +
	"\n" +
	"_user_nameB\f\n" +
	"\n" +
	"_share_urlB\x0e\n" +
	"\f_scope_countB\x12\n" +
	"\x10_antispam_ticketB\a\n" +
	"\x05_ssidB\x06\n" +
	"\x04_midB\f\n" +
	"\n" +
	"_deep_linkB\x16\n" +
	"\x14_jsapi_control_bytesB\x14\n" +
	"\x12_http_header_countB\n" +
	"\n" +
	"\b_wordingB\t\n" +
	"\a_avatarB\t\n" +
	"\a_cookieB\x0f\n" +
	"\r_menu_wording\"\x9a\x04\n" +
	"\x16JSAPIPreVerifyResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x12X\n" +
	"\fjsapi_result\x18\x02 \x01(\v20.api.official.JSAPIPreVerifyResponse.JSAPIResultH\x01R\vjsapiResult\x88\x01\x01\x12(\n" +
	"\x10verify_info_list\x18\x03 \x03(\tR\x0everifyInfoList\x12(\n" +
	"\x10domain_path_list\x18\x04 \x03(\tR\x0edomainPathList\x12)\n" +
	"\x0eapp_avatar_url\x18\x05 \x01(\tH\x02R\fappAvatarUrl\x88\x01\x01\x12&\n" +
	"\fapp_nickname\x18\x06 \x01(\tH\x03R\vappNickname\x88\x01\x01\x1av\n" +
	"\vJSAPIResult\x12\x17\n" +
	"\x04code\x18\x01 \x01(\x05H\x00R\x04code\x88\x01\x01\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x01R\x05error\x88\x01\x01\x12\x17\n" +
	"\x04json\x18\x03 \x01(\tH\x02R\x04json\x88\x01\x01B\a\n" +
	"\x05_codeB\b\n" +
	"\x06_errorB\a\n" +
	"\x05_jsonB\x10\n" +
	"\x0e_base_responseB\x0f\n" +
	"\r_jsapi_resultB\x11\n" +
	"\x0f_app_avatar_urlB\x0f\n" +
	"\r_app_nickname\"\x93\x04\n" +
	"\x16OauthAuthorizeResponse\x12@\n" +
	"\rbase_response\x18\x01 \x01(\v2\x16.api.base.BaseResponseH\x00R\fbaseResponse\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"scope_list\x18\x02 \x03(\fR\tscopeList\x12\x1e\n" +
	"\bapp_name\x18\x04 \x01(\tH\x01R\aappName\x88\x01\x01\x12%\n" +
	"\fapp_icon_url\x18\x05 \x01(\tH\x02R\n" +
	"appIconUrl\x88\x01\x01\x12&\n" +
	"\fredirect_url\x18\x06 \x01(\tH\x03R\vredirectUrl\x88\x01\x01\x120\n" +
	"\x12is_recent_has_auth\x18\t \x01(\bH\x04R\x0fisRecentHasAuth\x88\x01\x01\x12)\n" +
	"\x0eis_silent_auth\x18\n" +
	" \x01(\bH\x05R\fisSilentAuth\x88\x01\x01\x12A\n" +
	"\x1bis_call_server_when_confirm\x18\v \x01(\bH\x06R\x17isCallServerWhenConfirm\x88\x01\x01B\x10\n" +
	"\x0e_base_responseB\v\n" +
	"\t_app_nameB\x0f\n" +
	"\r_app_icon_urlB\x0f\n" +
	"\r_redirect_urlB\x15\n" +
	"\x13_is_recent_has_authB\x11\n" +
	"\x0f_is_silent_authB\x1e\n" +
	"\x1c_is_call_server_when_confirm\"\xce\x01\n" +
	"\rArticleResult\x12#\n" +
	"\rresponse_body\x18\x01 \x01(\tR\fresponseBody\x12\x18\n" +
	"\acookies\x18\x02 \x01(\tR\acookies\x12B\n" +
	"\aheaders\x18\x03 \x03(\v2(.api.official.ArticleResult.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B9Z7github.com/sbgayhub/golem/host/api/official;officialapib\x06proto3"

var (
	file_api_official_official_api_proto_rawDescOnce sync.Once
	file_api_official_official_api_proto_rawDescData []byte
)

func file_api_official_official_api_proto_rawDescGZIP() []byte {
	file_api_official_official_api_proto_rawDescOnce.Do(func() {
		file_api_official_official_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_official_official_api_proto_rawDesc), len(file_api_official_official_api_proto_rawDesc)))
	})
	return file_api_official_official_api_proto_rawDescData
}

var file_api_official_official_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_official_official_api_proto_goTypes = []any{
	(*GetA8KeyResponse)(nil),                       // 0: api.official.GetA8KeyResponse
	(*JSAPIPreVerifyResponse)(nil),                 // 1: api.official.JSAPIPreVerifyResponse
	(*OauthAuthorizeResponse)(nil),                 // 2: api.official.OauthAuthorizeResponse
	(*ArticleResult)(nil),                          // 3: api.official.ArticleResult
	(*GetA8KeyResponse_JSAPIPermissionBitSet)(nil), // 4: api.official.GetA8KeyResponse.JSAPIPermissionBitSet
	(*GetA8KeyResponse_BizScopeInfo)(nil),          // 5: api.official.GetA8KeyResponse.BizScopeInfo
	(*GetA8KeyResponse_HttpHeader)(nil),            // 6: api.official.GetA8KeyResponse.HttpHeader
	(*JSAPIPreVerifyResponse_JSAPIResult)(nil),     // 7: api.official.JSAPIPreVerifyResponse.JSAPIResult
	nil,                            // 8: api.official.ArticleResult.HeadersEntry
	(*base.BaseResponse)(nil),      // 9: api.base.BaseResponse
	(*wrapperspb.UInt32Value)(nil), // 10: google.protobuf.UInt32Value
	(*wrapperspb.UInt64Value)(nil), // 11: google.protobuf.UInt64Value
	(*base.Buffer)(nil),            // 12: api.base.Buffer
	(*wrapperspb.StringValue)(nil), // 13: google.protobuf.StringValue
}
var file_api_official_official_api_proto_depIdxs = []int32{
	9,  // 0: api.official.GetA8KeyResponse.base_response:type_name -> api.base.BaseResponse
	4,  // 1: api.official.GetA8KeyResponse.jsapi_permission:type_name -> api.official.GetA8KeyResponse.JSAPIPermissionBitSet
	10, // 2: api.official.GetA8KeyResponse.general_control:type_name -> google.protobuf.UInt32Value
	5,  // 3: api.official.GetA8KeyResponse.scope_list:type_name -> api.official.GetA8KeyResponse.BizScopeInfo
	11, // 4: api.official.GetA8KeyResponse.deep_link:type_name -> google.protobuf.UInt64Value
	12, // 5: api.official.GetA8KeyResponse.jsapi_control_bytes:type_name -> api.base.Buffer
	6,  // 6: api.official.GetA8KeyResponse.http_header_list:type_name -> api.official.GetA8KeyResponse.HttpHeader
	12, // 7: api.official.GetA8KeyResponse.cookie:type_name -> api.base.Buffer
	9,  // 8: api.official.JSAPIPreVerifyResponse.base_response:type_name -> api.base.BaseResponse
	7,  // 9: api.official.JSAPIPreVerifyResponse.jsapi_result:type_name -> api.official.JSAPIPreVerifyResponse.JSAPIResult
	9,  // 10: api.official.OauthAuthorizeResponse.base_response:type_name -> api.base.BaseResponse
	8,  // 11: api.official.ArticleResult.headers:type_name -> api.official.ArticleResult.HeadersEntry
	13, // 12: api.official.GetA8KeyResponse.BizScopeInfo.api_list:type_name -> google.protobuf.StringValue
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_official_official_api_proto_init() }
func file_api_official_official_api_proto_init() {
	if File_api_official_official_api_proto != nil {
		return
	}
	file_api_official_official_api_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_official_official_api_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_official_official_api_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_official_official_api_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_official_official_api_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_official_official_api_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_official_official_api_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_official_official_api_proto_rawDesc), len(file_api_official_official_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_official_official_api_proto_goTypes,
		DependencyIndexes: file_api_official_official_api_proto_depIdxs,
		MessageInfos:      file_api_official_official_api_proto_msgTypes,
	}.Build()
	File_api_official_official_api_proto = out.File
	file_api_official_official_api_proto_goTypes = nil
	file_api_official_official_api_proto_depIdxs = nil
}
